/**
 * @file auth.ts
 * @description Fastify JWT authentication plugin
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import fp from 'fastify-plugin';
import { authService } from '../services/auth.service';

export interface AuthenticatedRequest extends FastifyRequest {
  user?: {
    sub: string;
    email: string;
    name: string;
    groups: string[];
  };
}

async function authPlugin(fastify: FastifyInstance) {
  // Skip authentication in development if not configured
  if (process.env.NODE_ENV === 'development' && !authService.isConfigured()) {
    fastify.log.warn('Authentication disabled in development mode');
    return;
  }

  fastify.addHook('onRequest', async (request: AuthenticatedRequest, reply: FastifyReply) => {
    // Skip authentication for health endpoint
    if (request.url === '/health') {
      return;
    }

    const authHeader = request.headers.authorization;
    
    if (!authHeader) {
      reply.code(401).send({ error: 'Missing authorization header' });
      return;
    }

    const token = authService.extractTokenFromHeader(authHeader);
    
    if (!token) {
      reply.code(401).send({ error: 'Invalid authorization header format' });
      return;
    }

    const user = await authService.validateToken(token);
    
    if (!user) {
      reply.code(401).send({ error: 'Invalid or expired token' });
      return;
    }

    request.user = user;
  });
}

export default fp(authPlugin, {
  name: 'auth',
});