/**
 * @file cors.ts
 * @description CORS configuration plugin
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

import { FastifyInstance } from 'fastify';
import fp from 'fastify-plugin';
import cors from '@fastify/cors';

async function corsPlugin(fastify: FastifyInstance) {
  const allowedOrigins = process.env.NODE_ENV === 'production'
    ? [
        'https://dashboard.home.arpa',
        'https://dashboard.domain.com',
      ]
    : [
        'http://localhost:5173',
        'http://localhost:3000',
        'http://127.0.0.1:5173',
        'http://127.0.0.1:3000',
      ];

  await fastify.register(cors, {
    origin: (origin, callback) => {
      if (!origin || allowedOrigins.includes(origin)) {
        callback(null, true);
      } else {
        callback(new Error('Not allowed by CORS'), false);
      }
    },
    credentials: true,
    methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
    allowedHeaders: ['Content-Type', 'Authorization', 'X-Requested-With'],
  });

  fastify.log.info(`CORS configured for ${process.env.NODE_ENV} mode`);
}

export default fp(corsPlugin, {
  name: 'cors',
});