<!--
  @file +page.svelte
  @description Docker management page
  @author Generated by OK Computer for Michal's Dashboard
  @date 2025-01-07
-->

<script lang="ts">
  import { onMount } from 'svelte';
  import { apiClient } from '$lib/api/client';
  import type { DockerContainer } from '$lib/api/client';
  import { Package, Play, Square, RotateCcw } from 'lucide-svelte';
  import { fade } from 'svelte/transition';

  let containers: DockerContainer[] = [];
  let loading = true;
  let error: string | null = null;
  let selectedContainer: DockerContainer | null = null;

  const loadContainers = async () => {
    try {
      containers = await apiClient.getDockerContainers(true);
      error = null;
    } catch (err) {
      error = 'Failed to load Docker containers';
      console.error('Docker error:', err);
    } finally {
      loading = false;
    }
  };

  const handleContainerAction = async (container: DockerContainer, action: 'start' | 'stop' | 'restart') => {
    try {
      await apiClient.dockerContainerAction(container.id, action);
      await loadContainers();
    } catch (err) {
      console.error(`Failed to ${action} container:`, err);
    }
  };

  const getStatusColor = (status: DockerContainer['status']) => {
    switch (status) {
      case 'running': return '#22c55e';
      case 'exited': return '#ef4444';
      case 'paused': return '#f59e0b';
      case 'restarting': return '#3b82f6';
      default: return '#6b7280';
    }
  };

  onMount(async () => {
    await loadContainers();
    // Refresh every 10 seconds
    setInterval(loadContainers, 10000);
  });
</script>

<svelte:head>
  <title>Docker - Dashboard</title>
</svelte:head>

<div class="docker-page">
  <div class="page-header">
    <div class="header-content">
      <Package size={32} />
      <h1>Zarządzanie Docker</h1>
      <p>Lista wszystkich kontenerów Docker</p>
    </div>
  </div>

  {#if loading}
    <div class="loading-container" transition:fade>
      <div class="loading-spinner"></div>
      <span>Ładowanie kontenerów...</span>
    </div>
  {:else if error}
    <div class="error-container" transition:fade>
      <Package size={32} />
      <span>{error}</span>
    </div>
  {:else}
    <div class="containers-grid" transition:fade>
      {#each containers as container}
        <div class="container-card">
          <div class="container-header">
            <h3>{container.name}</h3>
            <div 
              class="status-badge"
              style="background-color: {getStatusColor(container.status)}"
            >
              {container.status}
            </div>
          </div>
          
          <div class="container-info">
            <div class="info-row">
              <span class="info-label">Image:</span>
              <span class="info-value">{container.image}</span>
            </div>
            <div class="info-row">
              <span class="info-label">ID:</span>
              <span class="info-value font-mono">{container.id}</span>
            </div>
            <div class="info-row">
              <span class="info-label">Status:</span>
              <span class="info-value">{container.state}</span>
            </div>
            {#if container.ports.length > 0}
              <div class="info-row">
                <span class="info-label">Ports:</span>
                <div class="ports-list">
                  {#each container.ports as port}
                    <span class="port-badge">
                      {port.publicPort ? `${port.publicPort}:` : ''}{port.privatePort}/{port.type}
                    </span>
                  {/each}
                </div>
              </div>
            {/if}
          </div>

          <div class="container-actions">
            {#if container.status !== 'running'}
              <button
                class="action-btn action-btn-start"
                on:click={() => handleContainerAction(container, 'start')}
                disabled={container.status === 'restarting'}
              >
                <Play size={16} />
                Start
              </button>
            {/if}
            
            {#if container.status === 'running'}
              <button
                class="action-btn action-btn-stop"
                on:click={() => handleContainerAction(container, 'stop')}
              >
                <Square size={16} />
                Stop
              </button>
            {/if}
            
            <button
              class="action-btn action-btn-restart"
              on:click={() => handleContainerAction(container, 'restart')}
              disabled={container.status === 'restarting'}
            >
              <RotateCcw size={16} />
              Restart
            </button>
          </div>
        </div>
      {/each}
    </div>
  {/if}
</div>

<style>
  .docker-page {
    padding: 2rem;
    min-height: 100vh;
  }

  .page-header {
    margin-bottom: 2rem;
    padding-bottom: 1rem;
    border-bottom: 1px solid var(--border);
  }

  .header-content {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    gap: 0.5rem;
  }

  .header-content :global(svg) {
    color: var(--accent-primary);
  }

  .header-content h1 {
    color: var(--text-primary);
    margin: 0;
  }

  .header-content p {
    color: var(--text-muted);
    margin: 0;
  }

  .loading-container,
  .error-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    min-height: 50vh;
    gap: 1rem;
    color: var(--text-muted);
  }

  .loading-spinner {
    width: 40px;
    height: 40px;
    border: 3px solid var(--border);
    border-top-color: var(--accent-primary);
    border-radius: 50%;
    animation: spin 1s linear infinite;
  }

  @keyframes spin {
    from { transform: rotate(0deg); }
    to { transform: rotate(360deg); }
  }

  .containers-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(400px, 1fr));
    gap: 1.5rem;
  }

  .container-card {
    background-color: var(--bg-card);
    border: 1px solid var(--border);
    border-radius: var(--radius-lg);
    padding: 1.5rem;
    transition: all var(--transition-fast);
  }

  .container-card:hover {
    border-color: var(--border-hover);
    box-shadow: var(--shadow-md);
  }

  .container-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 1rem;
  }

  .container-header h3 {
    color: var(--text-primary);
    margin: 0;
    font-size: 1.125rem;
  }

  .status-badge {
    padding: 0.25rem 0.75rem;
    border-radius: var(--radius-md);
    font-size: 0.75rem;
    font-weight: 500;
    color: white;
    text-transform: capitalize;
  }

  .container-info {
    margin-bottom: 1.5rem;
  }

  .info-row {
    display: flex;
    margin-bottom: 0.5rem;
    
    &:last-child {
      margin-bottom: 0;
    }
  }

  .info-label {
    color: var(--text-muted);
    font-weight: 500;
    min-width: 60px;
  }

  .info-value {
    color: var(--text-secondary);
    flex: 1;
  }

  .ports-list {
    display: flex;
    flex-wrap: wrap;
    gap: 0.25rem;
  }

  .port-badge {
    padding: 0.125rem 0.5rem;
    background-color: var(--bg-secondary);
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    font-size: 0.75rem;
    font-family: 'JetBrains Mono', monospace;
  }

  .container-actions {
    display: flex;
    gap: 0.5rem;
  }

  .action-btn {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.5rem 1rem;
    border: none;
    border-radius: var(--radius-md);
    font-size: 0.875rem;
    font-weight: 500;
    cursor: pointer;
    transition: all var(--transition-fast);
  }

  .action-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .action-btn-start {
    background-color: #22c55e;
    color: white;
  }

  .action-btn-start:hover:not(:disabled) {
    background-color: #16a34a;
  }

  .action-btn-stop {
    background-color: #ef4444;
    color: white;
  }

  .action-btn-stop:hover:not(:disabled) {
    background-color: #dc2626;
  }

  .action-btn-restart {
    background-color: #3b82f6;
    color: white;
  }

  .action-btn-restart:hover:not(:disabled) {
    background-color: #2563eb;
  }

  @media (max-width: 640px) {
    .docker-page {
      padding: 1rem;
    }

    .containers-grid {
      grid-template-columns: 1fr;
      gap: 1rem;
    }

    .container-card {
      padding: 1rem;
    }

    .container-actions {
      flex-direction: column;
    }
  }
</style>