/**
 * @file migrate.ts
 * @description Database migration runner
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { db } from './client';

async function runMigrations() {
  console.log('Running database migrations...');
  
  try {
    await migrate(db, { migrationsFolder: './migrations' });
    console.log('Migrations completed successfully');
  } catch (error) {
    console.error('Migration failed:', error);
    process.exit(1);
  }
}

runMigrations();