/**
 * @file schema.ts
 * @description Database schema definitions using Drizzle ORM
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

import { pgTable, uuid, text, timestamp, jsonb, boolean } from 'drizzle-orm/pg-core';
import { createInsertSchema, createSelectSchema } from 'drizzle-zod';
import { z } from 'zod';

export const widgets = pgTable('widgets', {
  id: uuid('id').primaryKey().defaultRandom(),
  type: text('type', { 
    enum: ['system-stats', 'docker-quick', 'pihole-stats', 'qbittorrent-stats', 'notes'] 
  }).notNull(),
  config: jsonb('config').notNull().default('{}'),
  position: jsonb('position').notNull().default('{}'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const auditLogs = pgTable('audit_logs', {
  id: uuid('id').primaryKey().defaultRandom(),
  action: text('action').notNull(),
  resource: text('resource').notNull(),
  metadata: jsonb('metadata'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const notes = pgTable('notes', {
  id: uuid('id').primaryKey().defaultRandom(),
  content: text('content').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

// Zod schemas for validation
export const widgetPositionSchema = z.object({
  x: z.number().int().min(0),
  y: z.number().int().min(0),
  w: z.number().int().min(1),
  h: z.number().int().min(1),
});

export const insertWidgetSchema = createInsertSchema(widgets, {
  position: widgetPositionSchema,
});

export const selectWidgetSchema = createSelectSchema(widgets);

export const insertNoteSchema = createInsertSchema(notes);
export const selectNoteSchema = createSelectSchema(notes);

export type Widget = z.infer<typeof selectWidgetSchema>;
export type NewWidget = z.infer<typeof insertWidgetSchema>;
export type Note = z.infer<typeof selectNoteSchema>;
export type NewNote = z.infer<typeof insertNoteSchema>;
export type WidgetType = 'system-stats' | 'docker-quick' | 'pihole-stats' | 'qbittorrent-stats' | 'notes';