<!--
  @file +layout.svelte
  @description Root layout with Navbar, Sidebar, and Footer
  @author Generated by OK Computer for Michal's Dashboard
  @date 2025-01-07
-->

<script lang="ts">
  import '../app.css';
  import Navbar from '$lib/components/Layout/Navbar.svelte';
  import Sidebar from '$lib/components/Layout/Sidebar.svelte';
  import Footer from '$lib/components/Layout/Footer.svelte';
  import { sidebarOpen } from '$lib/stores/sidebar';
  import { page } from '$app/stores';

  // Close sidebar when navigating (mobile)
  $: if ($page.url.pathname && $sidebarOpen && window.innerWidth < 769) {
    sidebarOpen.set(false);
  }
</script>

<div class="app-layout">
  <Navbar />
  
  <div class="main-container">
    <Sidebar />
    
    <main class="main-content">
      <slot />
    </main>
  </div>
  
  <Footer />
</div>

<style>
  .app-layout {
    display: flex;
    flex-direction: column;
    min-height: 100vh;
    background-color: var(--bg-primary);
  }

  .main-container {
    display: flex;
    flex: 1;
    position: relative;
  }

  .main-content {
    flex: 1;
    min-width: 0;
    padding: 0;
    margin-left: 0;
    transition: margin-left var(--transition-normal);
  }

  /* Desktop: show sidebar alongside content */
  @media (min-width: 769px) {
    .main-content {
      margin-left: 280px;
    }

    :global(.sidebar) {
      position: fixed;
      left: 0;
      top: 0;
      height: 100vh;
      z-index: 100;
    }

    :global(.navbar) {
      left: 280px;
      width: calc(100% - 280px);
    }

    :global(.footer) {
      left: 280px;
      width: calc(100% - 280px);
    }
  }

  /* Mobile: full width content */
  @media (max-width: 768px) {
    .main-content {
      margin-left: 0;
    }

    :global(.navbar) {
      left: 0;
      width: 100%;
    }

    :global(.footer) {
      left: 0;
      width: 100%;
    }
  }
</style>