<!--
  @file +page.svelte
  @description Main dashboard page with drag-and-drop widget grid
  @author Generated by OK Computer for Michal's Dashboard
  @date 2025-01-07
-->

<script lang="ts">
  import { onMount } from 'svelte';
  import WidgetGrid from '$lib/components/Grid/WidgetGrid.svelte';
  import WidgetWrapper from '$lib/components/Grid/WidgetWrapper.svelte';
  import SystemStats from '$lib/widgets/SystemStats.svelte';
  import { widgets, widgetsLoading, widgetsError } from '$lib/stores/widgets';
  import { apiClient } from '$lib/api/client';
  import { getWidgetDefinition } from '$lib/widgets/registry';
  import { Plus, X } from 'lucide-svelte';
  import { fade, scale } from 'svelte/transition';

  let showAddWidgetModal = false;
  let selectedWidgetType: string | null = null;

  const widgetComponents = {
    'system-stats': SystemStats,
    // Add other widget components here as they're created
  };

  const handleAddWidget = async (type: string) => {
    try {
      const definition = getWidgetDefinition(type);
      if (!definition) return;

      const newWidget = await apiClient.createWidget({
        type: type as any,
        config: {},
        position: {
          x: 0,
          y: 0,
          w: definition.defaultSize.w,
          h: definition.defaultSize.h,
        },
      });

      $widgets = [...$widgets, newWidget];
      showAddWidgetModal = false;
    } catch (error) {
      console.error('Failed to add widget:', error);
    }
  };

  const handleRemoveWidget = async (widget: any) => {
    try {
      await apiClient.deleteWidget(widget.id);
      $widgets = $widgets.filter(w => w.id !== widget.id);
    } catch (error) {
      console.error('Failed to remove widget:', error);
    }
  };

  const handleWidgetSettings = (widget: any) => {
    // TODO: Implement widget settings modal
    console.log('Widget settings:', widget);
  };

  onMount(async () => {
    try {
      widgetsLoading.set(true);
      const widgetList = await apiClient.getWidgets();
      widgets.set(widgetList);
    } catch (error) {
      widgetsError.set('Failed to load widgets');
      console.error('Failed to load widgets:', error);
    } finally {
      widgetsLoading.set(false);
    }
  });
</script>

<svelte:head>
  <title>Dashboard - Personal All-in-One</title>
</svelte:head>

<div class="dashboard-container">
  <WidgetGrid>
    {#each $widgets as widget (widget.id)}
      <div gs-id={widget.id}>
        <WidgetWrapper
          {widget}
          on:remove={(e) => handleRemoveWidget(e.detail)}
          on:settings={(e) => handleWidgetSettings(e.detail)}
        >
          {#if widgetComponents[widget.type]}
            <svelte:component 
              this={widgetComponents[widget.type]} 
              widgetId={widget.id}
              config={widget.config}
            />
          {:else}
            <div class="widget-placeholder">
              <h4>{widget.type}</h4>
              <p>Widget w budowie...</p>
            </div>
          {/if}
        </WidgetWrapper>
      </div>
    {/each}
  </WidgetGrid>

  <!-- Add Widget Modal -->
  {#if showAddWidgetModal}
    <div class="modal-overlay" transition:fade={{ duration: 200 }}>
      <div class="modal-content" transition:scale={{ duration: 200 }}>
        <div class="modal-header">
          <h3>Dodaj widget</h3>
          <button 
            class="close-btn"
            on:click={() => showAddWidgetModal = false}
            aria-label="Close modal"
          >
            <X size={20} />
          </button>
        </div>
        
        <div class="modal-body">
          <div class="widget-options">
            {#each Object.entries(widgetComponents) as [type, component]}
              {@const definition = getWidgetDefinition(type)}
              {#if definition}
                <button
                  class="widget-option"
                  on:click={() => handleAddWidget(type)}
                >
                  <div class="widget-icon">
                    {definition.icon}
                  </div>
                  <div class="widget-info">
                    <h4>{definition.name}</h4>
                    <p>{definition.description}</p>
                  </div>
                </button>
              {/if}
            {/each}
          </div>
        </div>
      </div>
    </div>
  {/if}

  <!-- Floating Add Button -->
  <button
    class="floating-add-btn"
    on:click={() => showAddWidgetModal = true}
    aria-label="Add widget"
  >
    <Plus size={24} />
  </button>
</div>

<style>
  .dashboard-container {
    min-height: 100vh;
    position: relative;
  }

  .widget-placeholder {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100%;
    color: var(--text-muted);
    text-align: center;
  }

  .widget-placeholder h4 {
    color: var(--text-primary);
    margin-bottom: 0.5rem;
    text-transform: capitalize;
  }

  .modal-overlay {
    position: fixed;
    inset: 0;
    background-color: rgba(0, 0, 0, 0.5);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1000;
    padding: 1rem;
  }

  .modal-content {
    background-color: var(--bg-card);
    border: 1px solid var(--border);
    border-radius: var(--radius-lg);
    max-width: 500px;
    width: 100%;
    max-height: 80vh;
    overflow-y: auto;
  }

  .modal-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1.5rem;
    border-bottom: 1px solid var(--border);
  }

  .modal-header h3 {
    color: var(--text-primary);
    margin: 0;
  }

  .close-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 32px;
    height: 32px;
    background: none;
    border: none;
    color: var(--text-muted);
    cursor: pointer;
    border-radius: var(--radius-sm);
    transition: all var(--transition-fast);
  }

  .close-btn:hover {
    color: var(--text-primary);
    background-color: var(--bg-hover);
  }

  .modal-body {
    padding: 1.5rem;
  }

  .widget-options {
    display: grid;
    gap: 0.75rem;
  }

  .widget-option {
    display: flex;
    align-items: center;
    gap: 1rem;
    padding: 1rem;
    background-color: var(--bg-secondary);
    border: 1px solid var(--border);
    border-radius: var(--radius-md);
    cursor: pointer;
    transition: all var(--transition-fast);
    text-align: left;
    width: 100%;
  }

  .widget-option:hover {
    border-color: var(--accent-primary);
    background-color: var(--accent-secondary);
  }

  .widget-icon {
    font-size: 2rem;
    flex-shrink: 0;
  }

  .widget-info h4 {
    color: var(--text-primary);
    margin: 0 0 0.25rem 0;
    font-size: 1rem;
  }

  .widget-info p {
    color: var(--text-muted);
    margin: 0;
    font-size: 0.875rem;
  }

  .floating-add-btn {
    position: fixed;
    bottom: 2rem;
    right: 2rem;
    width: 56px;
    height: 56px;
    background-color: var(--accent-primary);
    color: var(--bg-primary);
    border: none;
    border-radius: 50%;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    box-shadow: var(--shadow-lg);
    transition: all var(--transition-fast);
    z-index: 100;
  }

  .floating-add-btn:hover {
    transform: scale(1.1);
    box-shadow: var(--shadow-glow);
  }

  @media (max-width: 640px) {
    .floating-add-btn {
      bottom: 1rem;
      right: 1rem;
      width: 48px;
      height: 48px;
    }

    .modal-content {
      margin: 1rem;
      max-height: calc(100vh - 2rem);
    }

    .widget-options {
      grid-template-columns: 1fr;
    }
  }
</style>