<!--
  @file InfluxDBGraph.svelte
  @description InfluxDB metrics visualization widget
  @author Generated by OK Computer for Michal's Dashboard
  @date 2025-01-07
-->

<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { Line } from 'svelte-chartjs';
  import {
    Chart as ChartJS,
    CategoryScale,
    LinearScale,
    PointElement,
    LineElement,
    Title,
    Tooltip,
    Legend,
    Filler,
  } from 'chart.js';
  import { Activity, TrendingUp, Settings } from 'lucide-svelte';
  import { fade } from 'svelte/transition';
  import { apiClient } from '$lib/api/client';

  ChartJS.register(
    CategoryScale,
    LinearScale,
    PointElement,
    LineElement,
    Title,
    Tooltip,
    Legend,
    Filler
  );

  export let widgetId: string;
  export let config: {
    measurement?: string;
    field?: string;
    interval?: string;
    color?: string;
  } = {};

  let loading = true;
  let error: string | null = null;
  let interval: NodeJS.Timeout;
  let showSettings = false;

  // Sample data structure for Chart.js
  let chartData = {
    labels: [] as string[],
    datasets: [
      {
        label: config.field || 'Wartość',
        data: [] as number[],
        borderColor: config.color || 'var(--accent-primary)',
        backgroundColor: (config.color || 'var(--accent-primary)') + '20',
        borderWidth: 2,
        fill: true,
        tension: 0.4,
        pointRadius: 3,
        pointHoverRadius: 5,
      },
    ],
  };

  let chartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        display: false,
      },
      tooltip: {
        mode: 'index',
        intersect: false,
        backgroundColor: 'var(--bg-card)',
        titleColor: 'var(--text-primary)',
        bodyColor: 'var(--text-secondary)',
        borderColor: 'var(--border)',
        borderWidth: 1,
        padding: 12,
        cornerRadius: 8,
        callbacks: {
          label: function (context: any) {
            return `${context.dataset.label}: ${context.parsed.y.toFixed(2)}`;
          },
        },
      },
    },
    scales: {
      x: {
        display: true,
        grid: {
          color: 'var(--border)',
        },
        ticks: {
          color: 'var(--text-muted)',
          font: {
            size: 10,
          },
        },
      },
      y: {
        display: true,
        grid: {
          color: 'var(--border)',
        },
        ticks: {
          color: 'var(--text-muted)',
          font: {
            size: 10,
          },
        },
      },
    },
    interaction: {
      mode: 'nearest',
      axis: 'x',
      intersect: false,
    },
  };

  // Mock data generator (replace with real InfluxDB API calls)
  const generateMockData = () => {
    const now = new Date();
    const labels = [];
    const data = [];
    
    // Generate 12 data points for the last hour
    for (let i = 11; i >= 0; i--) {
      const time = new Date(now.getTime() - i * 5 * 60 * 1000); // 5 minute intervals
      labels.push(time.toLocaleTimeString('pl-PL', { hour: '2-digit', minute: '2-digit' }));
      
      // Generate realistic mock data based on config
      let value: number;
      switch (config.measurement) {
        case 'cpu':
          value = 20 + Math.random() * 60 + Math.sin(Date.now() / 10000) * 20;
          break;
        case 'memory':
          value = 40 + Math.random() * 40;
          break;
        case 'disk':
          value = 10 + Math.random() * 30;
          break;
        case 'network':
          value = Math.random() * 100;
          break;
        default:
          value = Math.random() * 100;
      }
      data.push(Math.max(0, value));
    }
    
    return { labels, data };
  };

  const loadMetrics = async () => {
    try {
      // In production, replace with real InfluxDB API call
      // const response = await apiClient.getInfluxDBData(config.measurement, config.interval);
      
      const mockData = generateMockData();
      
      chartData = {
        ...chartData,
        labels: mockData.labels,
        datasets: [
          {
            ...chartData.datasets[0],
            data: mockData.data,
            label: config.field || 'Wartość',
          },
        ],
      };
      
      error = null;
    } catch (err) {
      error = 'Failed to load metrics';
      console.error('InfluxDB error:', err);
    } finally {
      loading = false;
    }
  };

  const saveSettings = () => {
    // Save settings to widget config
    showSettings = false;
    loadMetrics();
  };

  onMount(async () => {
    await loadMetrics();
    // Refresh every 30 seconds
    interval = setInterval(loadMetrics, 30000);
  });

  onDestroy(() => {
    if (interval) {
      clearInterval(interval);
    }
  });
</script>

{#if loading}
  <div class="loading-container" transition:fade>
    <div class="loading-spinner"></div>
    <span>Ładowanie metryk...</span>
  </div>
{:else if error}
  <div class="error-container" transition:fade>
    <Activity size={32} />
    <span>{error}</span>
    <button class="retry-btn" on:click={loadMetrics}>Spróbuj ponownie</button>
  </div>
{:else}
  <div class="influx-container" transition:fade>
    <!-- Header -->
    <div class="widget-header">
      <div class="header-info">
        <TrendingUp size={20} />
        <div class="header-text">
          <h4>{config.measurement || 'Metryki systemowe'}</h4>
          <span class="subtitle">{config.field || 'Wartość'}</span>
        </div>
      </div>
      <button 
        class="settings-btn"
        on:click={() => showSettings = !showSettings}
        title="Ustawienia"
      >
        <Settings size={16} />
      </button>
    </div>

    <!-- Chart -->
    <div class="chart-container">
      <Line data={chartData} options={chartOptions} />
    </div>

    <!-- Current Value Display -->
    <div class="current-value">
      <span class="value">
        {chartData.datasets[0].data.length > 0 
          ? chartData.datasets[0].data[chartData.datasets[0].data.length - 1].toFixed(2)
          : '0.00'}
      </span>
      <span class="unit">
        {config.measurement === 'cpu' ? '%' : 
         config.measurement === 'memory' ? '%' :
         config.measurement === 'network' ? 'MB/s' : ''}
      </span>
    </div>
  </div>
{/if}

<!-- Settings Modal -->
{#if showSettings}
  <div class="settings-overlay" transition:fade on:click={() => showSettings = false}>
    <div class="settings-modal" transition:scale on:click|stopPropagation>
      <div class="settings-header">
        <h4>Ustawienia wykresu</h4>
        <button class="close-btn" on:click={() => showSettings = false}>×</button>
      </div>
      
      <div class="settings-body">
        <div class="form-group">
          <label for="measurement">Pomiar</label>
          <select id="measurement" bind:value={config.measurement}>
            <option value="cpu">CPU</option>
            <option value="memory">Pamięć</option>
            <option value="disk">Dysk</option>
            <option value="network">Sieć</option>
          </select>
        </div>
        
        <div class="form-group">
          <label for="field">Pole</label>
          <input id="field" type="text" bind:value={config.field} placeholder="użycie_procesora" />
        </div>
        
        <div class="form-group">
          <label for="interval">Interwał</label>
          <select id="interval" bind:value={config.interval}>
            <option value="5m">5 minut</option>
            <option value="15m">15 minut</option>
            <option value="1h">1 godzina</option>
            <option value="6h">6 godzin</option>
          </select>
        </div>
        
        <div class="form-group">
          <label for="color">Kolor</label>
          <input id="color" type="color" bind:value={config.color} />
        </div>
      </div>
      
      <div class="settings-footer">
        <button class="btn-secondary" on:click={() => showSettings = false}>Anuluj</button>
        <button class="btn-primary" on:click={saveSettings}>Zapisz</button>
      </div>
    </div>
  </div>
{/if}

<style>
  .loading-container,
  .error-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100%;
    gap: 1rem;
    color: var(--text-muted);
    text-align: center;
  }

  .loading-spinner {
    width: 32px;
    height: 32px;
    border: 2px solid var(--border);
    border-top-color: var(--accent-primary);
    border-radius: 50%;
    animation: spin 1s linear infinite;
  }

  @keyframes spin {
    from { transform: rotate(0deg); }
    to { transform: rotate(360deg); }
  }

  .retry-btn {
    padding: 0.5rem 1rem;
    background-color: var(--accent-primary);
    color: var(--bg-primary);
    border: none;
    border-radius: var(--radius-md);
    font-size: 0.875rem;
    cursor: pointer;
    transition: all var(--transition-fast);
  }

  .retry-btn:hover {
    filter: brightness(1.1);
  }

  .influx-container {
    display: flex;
    flex-direction: column;
    height: 100%;
    padding: 0.5rem;
  }

  .widget-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 1rem;
    padding-bottom: 0.5rem;
    border-bottom: 1px solid var(--border);
  }

  .header-info {
    display: flex;
    align-items: center;
    gap: 0.75rem;
  }

  .header-info :global(svg) {
    color: var(--accent-primary);
  }

  .header-text h4 {
    color: var(--text-primary);
    margin: 0 0 0.25rem 0;
    font-size: 0.875rem;
  }

  .subtitle {
    color: var(--text-muted);
    font-size: 0.75rem;
  }

  .settings-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 28px;
    height: 28px;
    background: none;
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    color: var(--text-muted);
    cursor: pointer;
    transition: all var(--transition-fast);
  }

  .settings-btn:hover {
    color: var(--text-primary);
    background-color: var(--bg-hover);
  }

  .chart-container {
    flex: 1;
    min-height: 200px;
    margin-bottom: 1rem;
  }

  .current-value {
    display: flex;
    align-items: baseline;
    justify-content: center;
    gap: 0.5rem;
    padding: 1rem;
    background-color: var(--bg-secondary);
    border-radius: var(--radius-md);
    border: 1px solid var(--border);
  }

  .value {
    font-size: 2rem;
    font-weight: 600;
    color: var(--accent-primary);
    font-family: 'JetBrains Mono', monospace;
  }

  .unit {
    font-size: 1rem;
    color: var(--text-muted);
  }

  .settings-overlay {
    position: fixed;
    inset: 0;
    background-color: rgba(0, 0, 0, 0.5);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1000;
    padding: 1rem;
  }

  .settings-modal {
    background-color: var(--bg-card);
    border: 1px solid var(--border);
    border-radius: var(--radius-lg);
    max-width: 400px;
    width: 100%;
    max-height: 80vh;
    overflow-y: auto;
  }

  .settings-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1rem;
    border-bottom: 1px solid var(--border);
  }

  .settings-header h4 {
    color: var(--text-primary);
    margin: 0;
  }

  .close-btn {
    background: none;
    border: none;
    color: var(--text-muted);
    font-size: 1.5rem;
    cursor: pointer;
    padding: 0;
    width: 24px;
    height: 24px;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .close-btn:hover {
    color: var(--text-primary);
  }

  .settings-body {
    padding: 1rem;
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .form-group {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  .form-group label {
    color: var(--text-secondary);
    font-size: 0.875rem;
    font-weight: 500;
  }

  .form-group input,
  .form-group select {
    padding: 0.5rem;
    background-color: var(--bg-secondary);
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    color: var(--text-primary);
    font-size: 0.875rem;
    transition: all var(--transition-fast);
  }

  .form-group input:focus,
  .form-group select:focus {
    outline: none;
    border-color: var(--accent-primary);
    box-shadow: 0 0 0 2px var(--accent-secondary);
  }

  .settings-footer {
    display: flex;
    justify-content: flex-end;
    gap: 0.75rem;
    padding: 1rem;
    border-top: 1px solid var(--border);
  }

  .btn-secondary,
  .btn-primary {
    padding: 0.5rem 1rem;
    border-radius: var(--radius-sm);
    font-size: 0.875rem;
    font-weight: 500;
    cursor: pointer;
    transition: all var(--transition-fast);
  }

  .btn-secondary {
    background-color: transparent;
    color: var(--text-secondary);
    border: 1px solid var(--border);
  }

  .btn-secondary:hover {
    background-color: var(--bg-hover);
    color: var(--text-primary);
  }

  .btn-primary {
    background-color: var(--accent-primary);
    color: var(--bg-primary);
    border: none;
  }

  .btn-primary:hover {
    filter: brightness(1.1);
  }

  @media (max-width: 640px) {
    .influx-container {
      padding: 0.25rem;
    }

    .chart-container {
      min-height: 150px;
    }

    .value {
      font-size: 1.5rem;
    }
  }
</style>