<!--
  @file PiholeStats.svelte
  @description Pi-hole statistics widget with real-time data
  @author Generated by OK Computer for Michal's Dashboard
  @date 2025-01-07
-->

<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { apiClient } from '$lib/api/client';
  import type { PiHoleStats } from '$lib/api/client';
  import { ShieldCheck, ShieldOff, Globe, Ban, Clock } from 'lucide-svelte';
  import { fade } from 'svelte/transition';
  import CircularProgress from '$lib/components/UI/CircularProgress.svelte';

  export let widgetId: string;

  let stats: PiHoleStats | null = null;
  let loading = true;
  let error: string | null = null;
  let interval: NodeJS.Timeout;
  let toggling = false;

  const loadStats = async () => {
    try {
      stats = await apiClient.getPiHoleStats();
      error = null;
    } catch (err) {
      error = 'Failed to load Pi-hole stats';
      console.error('Pi-hole error:', err);
    } finally {
      loading = false;
    }
  };

  const togglePiHole = async () => {
    if (!stats || toggling) return;
    
    toggling = true;
    try {
      await apiClient.togglePiHole(stats.status === 'disabled');
      await loadStats();
    } catch (err) {
      console.error('Failed to toggle Pi-hole:', err);
    } finally {
      toggling = false;
    }
  };

  onMount(async () => {
    await loadStats();
    // Refresh every 30 seconds
    interval = setInterval(loadStats, 30000);
  });

  onDestroy(() => {
    if (interval) {
      clearInterval(interval);
    }
  });
</script>

{#if loading}
  <div class="loading-container" transition:fade>
    <div class="loading-spinner"></div>
    <span>Ładowanie statystyk Pi-hole...</span>
  </div>
{:else if error}
  <div class="error-container" transition:fade>
    <ShieldOff size={32} />
    <span>{error}</span>
  </div>
{:else if stats}
  <div class="pihole-container" transition:fade>
    <!-- Status Header -->
    <div class="status-header">
      <div class="status-indicator" class:enabled={stats.status === 'enabled'}>
        <ShieldCheck size={20} />
        <span>Pi-hole {stats.status === 'enabled' ? 'aktywny' : 'nieaktywny'}</span>
      </div>
      <button 
        class="toggle-btn"
        on:click={togglePiHole}
        disabled={toggling}
        class:loading={toggling}
      >
        {toggling ? 'Zmienianie...' : (stats.status === 'enabled' ? 'Wyłącz' : 'Włącz')}
      </button>
    </div>

    <!-- Statistics Grid -->
    <div class="stats-grid">
      <div class="stat-item">
        <div class="stat-icon">
          <Globe size={24} />
        </div>
        <div class="stat-content">
          <span class="stat-value">{stats.queries_today.toLocaleString()}</span>
          <span class="stat-label">Zapytania dzisiaj</span>
        </div>
      </div>

      <div class="stat-item">
        <div class="stat-icon">
          <Ban size={24} />
        </div>
        <div class="stat-content">
          <span class="stat-value">{stats.blocked_today.toLocaleString()}</span>
          <span class="stat-label">Zablokowane dzisiaj</span>
        </div>
      </div>
    </div>

    <!-- Percentage Blocked -->
    <div class="percentage-section">
      <div class="percentage-header">
        <span class="percentage-label">Procent zablokowanych</span>
        <span class="percentage-value">{stats.percentage_blocked}%</span>
      </div>
      <div class="percentage-bar">
        <div 
          class="percentage-fill" 
          style="width: {Math.min(stats.percentage_blocked, 100)}%"
        ></div>
      </div>
    </div>

    <!-- Additional Stats -->
    <div class="additional-stats">
      <div class="additional-item">
        <Clock size={16} />
        <span>Klienci: {stats.unique_clients}</span>
      </div>
      <div class="additional-item">
        <Ban size={16} />
        <span>Domeny na liście: {stats.domains_being_blocked.toLocaleString()}</span>
      </div>
    </div>
  </div>
{/if}

<style>
  .loading-container,
  .error-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100%;
    gap: 1rem;
    color: var(--text-muted);
    text-align: center;
  }

  .loading-spinner {
    width: 32px;
    height: 32px;
    border: 2px solid var(--border);
    border-top-color: var(--accent-primary);
    border-radius: 50%;
    animation: spin 1s linear infinite;
  }

  @keyframes spin {
    from { transform: rotate(0deg); }
    to { transform: rotate(360deg); }
  }

  .pihole-container {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    padding: 0.5rem;
  }

  .status-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding-bottom: 1rem;
    border-bottom: 1px solid var(--border);
  }

  .status-indicator {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    color: var(--text-muted);
    font-weight: 500;
  }

  .status-indicator.enabled {
    color: #22c55e;
  }

  .toggle-btn {
    padding: 0.5rem 1rem;
    background-color: var(--accent-primary);
    color: var(--bg-primary);
    border: none;
    border-radius: var(--radius-md);
    font-size: 0.875rem;
    font-weight: 500;
    cursor: pointer;
    transition: all var(--transition-fast);
  }

  .toggle-btn:hover:not(:disabled) {
    filter: brightness(1.1);
    transform: translateY(-1px);
  }

  .toggle-btn:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .toggle-btn.loading {
    animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
  }

  .stats-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 1rem;
  }

  .stat-item {
    display: flex;
    align-items: center;
    gap: 1rem;
    padding: 1rem;
    background-color: var(--bg-secondary);
    border-radius: var(--radius-md);
    border: 1px solid var(--border);
  }

  .stat-icon {
    color: var(--accent-primary);
    flex-shrink: 0;
  }

  .stat-content {
    display: flex;
    flex-direction: column;
  }

  .stat-value {
    font-size: 1.25rem;
    font-weight: 600;
    color: var(--text-primary);
  }

  .stat-label {
    font-size: 0.75rem;
    color: var(--text-muted);
    margin-top: 0.25rem;
  }

  .percentage-section {
    padding: 1rem;
    background-color: var(--bg-secondary);
    border-radius: var(--radius-md);
    border: 1px solid var(--border);
  }

  .percentage-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 0.75rem;
  }

  .percentage-label {
    font-size: 0.875rem;
    color: var(--text-muted);
  }

  .percentage-value {
    font-size: 1.125rem;
    font-weight: 600;
    color: var(--accent-primary);
  }

  .percentage-bar {
    height: 8px;
    background-color: var(--border);
    border-radius: 4px;
    overflow: hidden;
  }

  .percentage-fill {
    height: 100%;
    background-color: var(--accent-primary);
    transition: width 0.5s ease-in-out;
    box-shadow: 0 0 10px var(--accent-primary);
  }

  .additional-stats {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    padding: 1rem;
    background-color: var(--bg-secondary);
    border-radius: var(--radius-md);
    border: 1px solid var(--border);
  }

  .additional-item {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-size: 0.875rem;
    color: var(--text-secondary);
  }

  @media (max-width: 640px) {
    .pihole-container {
      padding: 0.25rem;
    }

    .stats-grid {
      grid-template-columns: 1fr;
      gap: 0.75rem;
    }

    .status-header {
      flex-direction: column;
      gap: 0.75rem;
      align-items: stretch;
    }
  }
</style>