/**
 * @file registry.ts
 * @description Widget type registry and definitions
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

import type { ComponentType } from 'svelte';
import type { Widget } from '$lib/api/client';

// Widget type definitions
export interface WidgetDefinition {
  type: Widget['type'];
  name: string;
  description: string;
  icon: string;
  defaultSize: { w: number; h: number };
  minSize?: { w: number; h: number };
  maxSize?: { w: number; h: number };
  category: 'system' | 'network' | 'media' | 'productivity';
}

// Widget registry
export const widgetRegistry: Record<Widget['type'], WidgetDefinition> = {
  'system-stats': {
    type: 'system-stats',
    name: 'System Stats',
    description: 'CPU, RAM, disk, and temperature monitoring',
    icon: 'activity',
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 4 },
    category: 'system',
  },
  'docker-quick': {
    type: 'docker-quick',
    name: 'Docker Quick Actions',
    description: 'Quick Docker container management',
    icon: 'container',
    defaultSize: { w: 3, h: 4 },
    minSize: { w: 2, h: 3 },
    maxSize: { w: 4, h: 6 },
    category: 'system',
  },
  'pihole-stats': {
    type: 'pihole-stats',
    name: 'Pi-hole Stats',
    description: 'Pi-hole DNS filtering statistics with toggle',
    icon: 'shield-check',
    defaultSize: { w: 3, h: 3 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 4, h: 4 },
    category: 'network',
  },
  'qbittorrent-stats': {
    type: 'qbittorrent-stats',
    name: 'qBittorrent Stats',
    description: 'qBittorrent download statistics and management',
    icon: 'download',
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    maxSize: { w: 6, h: 5 },
    category: 'media',
  },
  'influxdb-graph': {
    type: 'influxdb-graph',
    name: 'InfluxDB Graph',
    description: 'System metrics visualization from InfluxDB',
    icon: 'activity',
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 4 },
    category: 'system',
  },
  'notes': {
    type: 'notes',
    name: 'Notes',
    description: 'Personal notes widget',
    icon: 'file-text',
    defaultSize: { w: 3, h: 4 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 6, h: 8 },
    category: 'productivity',
  },
};

// Get widget definition by type
export function getWidgetDefinition(type: Widget['type']): WidgetDefinition | undefined {
  return widgetRegistry[type];
}

// Get all widget definitions
export function getAllWidgetDefinitions(): WidgetDefinition[] {
  return Object.values(widgetRegistry);
}

// Get widgets by category
export function getWidgetsByCategory(category: WidgetDefinition['category']): WidgetDefinition[] {
  return Object.values(widgetRegistry).filter(widget => widget.category === category);
}

// Check if widget type exists
export function isValidWidgetType(type: string): type is Widget['type'] {
  return type in widgetRegistry;
}

// Get widget categories
export function getWidgetCategories(): WidgetDefinition['category'][] {
  return ['system', 'network', 'media', 'productivity'];
}