<!--
  @file SystemStats.svelte
  @description System statistics widget (CPU, RAM, disk, temperature)
  @author Generated by OK Computer for Michal's Dashboard
  @date 2025-01-07
-->

<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { apiClient } from '$lib/api/client';
  import type { SystemStats } from '$lib/api/client';
  import { Activity, Cpu, HardDrive, Thermometer } from 'lucide-svelte';
  import CircularProgress from '$lib/components/UI/CircularProgress.svelte';

  export let widgetId: string;

  let stats: SystemStats | null = null;
  let loading = true;
  let error: string | null = null;
  let interval: NodeJS.Timeout;

  const loadStats = async () => {
    try {
      stats = await apiClient.getSystemStats();
      error = null;
    } catch (err) {
      error = 'Failed to load system stats';
      console.error('System stats error:', err);
    } finally {
      loading = false;
    }
  };

  onMount(async () => {
    await loadStats();
    // Refresh every 5 seconds
    interval = setInterval(loadStats, 5000);
  });

  onDestroy(() => {
    if (interval) {
      clearInterval(interval);
    }
  });

  const formatBytes = (bytes: number): string => {
    const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
    if (bytes === 0) return '0 B';
    const i = Math.floor(Math.log(bytes) / Math.log(1024));
    return Math.round(bytes / Math.pow(1024, i) * 100) / 100 + ' ' + sizes[i];
  };

  const formatUptime = (seconds: number): string => {
    const days = Math.floor(seconds / 86400);
    const hours = Math.floor((seconds % 86400) / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    
    if (days > 0) {
      return `${days}d ${hours}h ${minutes}m`;
    } else if (hours > 0) {
      return `${hours}h ${minutes}m`;
    } else {
      return `${minutes}m`;
    }
  };
</script>

{#if loading}
  <div class="loading-container">
    <div class="loading-spinner"></div>
    <span>Ładowanie statystyk...</span>
  </div>
{:else if error}
  <div class="error-container">
    <Activity size={32} />
    <span>{error}</span>
  </div>
{:else if stats}
  <div class="stats-grid">
    <div class="stat-item">
      <div class="stat-header">
        <Cpu size={16} />
        <span class="stat-label">CPU</span>
      </div>
      <CircularProgress value={stats.cpu.usage} max={100} size={60} />
      <div class="stat-value">{stats.cpu.usage}%</div>
      <div class="stat-subtitle">{stats.cpu.cores} rdzeni</div>
    </div>

    <div class="stat-item">
      <div class="stat-header">
        <Activity size={16} />
        <span class="stat-label">RAM</span>
      </div>
      <CircularProgress value={stats.ram.percentage} max={100} size={60} />
      <div class="stat-value">{stats.ram.percentage}%</div>
      <div class="stat-subtitle">{stats.ram.used}GB / {stats.ram.total}GB</div>
    </div>

    <div class="stat-item">
      <div class="stat-header">
        <HardDrive size={16} />
        <span class="stat-label">Dysk</span>
      </div>
      <CircularProgress value={stats.disk.percentage} max={100} size={60} />
      <div class="stat-value">{stats.disk.percentage}%</div>
      <div class="stat-subtitle">{stats.disk.used}GB / {stats.disk.total}GB</div>
    </div>

    <div class="stat-item">
      <div class="stat-header">
        <Thermometer size={16} />
        <span class="stat-label">Temp.</span>
      </div>
      <div class="temp-display">
        {#if stats.temp.value !== null}
          <span class="temp-value">{stats.temp.value}°{stats.temp.unit}</span>
        {:else}
          <span class="temp-value">N/A</span>
        {/if}
      </div>
      <div class="stat-subtitle">Uptime: {formatUptime(stats.uptime)}</div>
    </div>
  </div>

  <div class="system-info">
    <div class="info-row">
      <span class="info-label">Host:</span>
      <span class="info-value">{stats.hostname}</span>
    </div>
    <div class="info-row">
      <span class="info-label">Platform:</span>
      <span class="info-value">{stats.platform} ({stats.arch})</span>
    </div>
  </div>
{/if}

<style>
  .loading-container,
  .error-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100%;
    gap: 1rem;
    color: var(--text-muted);
    text-align: center;
  }

  .loading-spinner {
    width: 32px;
    height: 32px;
    border: 2px solid var(--border);
    border-top-color: var(--accent-primary);
    border-radius: 50%;
    animation: spin 1s linear infinite;
  }

  @keyframes spin {
    from { transform: rotate(0deg); }
    to { transform: rotate(360deg); }
  }

  .stats-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 1rem;
    margin-bottom: 1rem;
  }

  .stat-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    padding: 0.75rem;
    background-color: var(--bg-secondary);
    border-radius: var(--radius-md);
  }

  .stat-header {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    margin-bottom: 0.5rem;
    font-size: 0.75rem;
    color: var(--text-muted);
  }

  .stat-label {
    font-weight: 500;
  }

  .stat-value {
    font-size: 1.25rem;
    font-weight: 600;
    color: var(--accent-primary);
    margin: 0.25rem 0;
  }

  .stat-subtitle {
    font-size: 0.7rem;
    color: var(--text-muted);
  }

  .temp-display {
    display: flex;
    align-items: center;
    justify-content: center;
    margin: 0.5rem 0;
  }

  .temp-value {
    font-size: 1.5rem;
    font-weight: 600;
    color: var(--accent-primary);
  }

  .system-info {
    padding: 0.75rem;
    background-color: var(--bg-secondary);
    border-radius: var(--radius-md);
    font-size: 0.75rem;
  }

  .info-row {
    display: flex;
    justify-content: space-between;
    margin-bottom: 0.25rem;
    
    &:last-child {
      margin-bottom: 0;
    }
  }

  .info-label {
    color: var(--text-muted);
    font-weight: 500;
  }

  .info-value {
    color: var(--text-secondary);
    font-family: 'JetBrains Mono', monospace;
  }

  @media (max-width: 640px) {
    .stats-grid {
      grid-template-columns: 1fr;
      gap: 0.75rem;
    }

    .stat-item {
      padding: 0.5rem;
    }
  }
</style>