/**
 * @file auth.service.ts
 * @description JWT validation service for Authentik integration
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

import { createRemoteJWKSet, jwtVerify, JWTPayload } from 'jose';
import { logger } from '../utils/logger';

interface AuthenticatedUser {
  sub: string;
  email: string;
  name: string;
  groups: string[];
}

class AuthService {
  private jwks: ReturnType<typeof createRemoteJWKSet> | null = null;
  private issuer: string;

  constructor() {
    this.issuer = process.env.AUTHENTIK_ISSUER || '';
    const jwksUrl = process.env.AUTHENTIK_JWKS_URL || '';

    if (this.issuer && jwksUrl) {
      try {
        this.jwks = createRemoteJWKSet(new URL(jwksUrl));
        logger.info('Auth service initialized with JWKS');
      } catch (error) {
        logger.error('Failed to initialize JWKS:', error);
      }
    } else {
      logger.warn('Auth service not configured - missing AUTHENTIK environment variables');
    }
  }

  async validateToken(token: string): Promise<AuthenticatedUser | null> {
    if (!this.jwks) {
      logger.warn('JWKS not initialized, skipping token validation');
      return null;
    }

    try {
      const { payload } = await jwtVerify(token, this.jwks, {
        issuer: this.issuer,
        algorithms: ['RS256'],
      });

      const user: AuthenticatedUser = {
        sub: payload.sub || '',
        email: payload.email as string || '',
        name: payload.name as string || '',
        groups: payload.groups as string[] || [],
      };

      logger.debug('Token validated for user:', user.email);
      return user;
    } catch (error) {
      logger.error('Token validation failed:', error);
      return null;
    }
  }

  isConfigured(): boolean {
    return this.jwks !== null;
  }

  extractTokenFromHeader(authHeader: string): string | null {
    if (!authHeader.startsWith('Bearer ')) {
      return null;
    }
    return authHeader.substring(7);
  }
}

export const authService = new AuthService();