/**
 * @file docker.ts
 * @description Docker API proxy endpoints
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { z } from 'zod';
import { dockerService } from '../services/docker.service';
import { logger } from '../utils/logger';

const containerActionSchema = z.object({
  action: z.enum(['start', 'stop', 'restart']),
});

const dockerQuerySchema = z.object({
  all: z.boolean().optional().default(false),
  limit: z.number().int().min(1).max(100).optional(),
});

export default async function dockerRoutes(fastify: FastifyInstance) {
  /**
   * @GET /api/docker/containers
   * @description Get list of Docker containers
   */
  fastify.get('/api/docker/containers', {
    schema: {
      tags: ['Docker'],
      summary: 'List containers',
      description: 'Retrieve list of Docker containers',
      querystring: {
        type: 'object',
        properties: {
          all: { type: 'boolean', description: 'Include stopped containers' },
          limit: { type: 'number', description: 'Limit number of results' },
        },
      },
      response: {
        200: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: { type: 'string' },
              name: { type: 'string' },
              image: { type: 'string' },
              status: { type: 'string' },
              state: { type: 'string' },
              ports: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: {
                    privatePort: { type: 'number' },
                    publicPort: { type: 'number' },
                    type: { type: 'string' },
                  },
                },
              },
              created: { type: 'string', format: 'date-time' },
            },
          },
        },
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    const query = dockerQuerySchema.parse(request.query);
    
    try {
      const containers = await dockerService.listContainers(query.all);
      const limitedContainers = query.limit 
        ? containers.slice(0, query.limit)
        : containers;
      
      reply.send(limitedContainers);
    } catch (error) {
      logger.error('Failed to fetch Docker containers:', error);
      reply.code(500).send({ error: 'Failed to fetch Docker containers' });
    }
  });

  /**
   * @GET /api/docker/containers/:id/stats
   * @description Get container statistics
   */
  fastify.get('/api/docker/containers/:id/stats', {
    schema: {
      tags: ['Docker'],
      summary: 'Get container stats',
      description: 'Retrieve container statistics',
      params: {
        type: 'object',
        properties: {
          id: { type: 'string' },
        },
        required: ['id'],
      },
      response: {
        200: {
          type: 'object',
          properties: {
            cpuUsage: { type: 'number' },
            memoryUsage: { type: 'number' },
            memoryLimit: { type: 'number' },
            networkIO: {
              type: 'object',
              properties: {
                rxBytes: { type: 'number' },
                txBytes: { type: 'number' },
              },
            },
          },
        },
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    const params = z.object({ id: z.string() }).parse(request.params);
    
    try {
      const stats = await dockerService.getContainerStats(params.id);
      reply.send(stats);
    } catch (error) {
      logger.error(`Failed to fetch container stats for ${params.id}:`, error);
      reply.code(500).send({ error: 'Failed to fetch container stats' });
    }
  });

  /**
   * @POST /api/docker/containers/:id/action
   * @description Perform action on container (start/stop/restart)
   */
  fastify.post('/api/docker/containers/:id/action', {
    schema: {
      tags: ['Docker'],
      summary: 'Container action',
      description: 'Perform action on Docker container',
      params: {
        type: 'object',
        properties: {
          id: { type: 'string' },
        },
        required: ['id'],
      },
      body: {
        type: 'object',
        properties: {
          action: { type: 'string', enum: ['start', 'stop', 'restart'] },
        },
        required: ['action'],
      },
      response: {
        200: {
          type: 'object',
          properties: {
            success: { type: 'boolean' },
            message: { type: 'string' },
          },
        },
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    const params = z.object({ id: z.string() }).parse(request.params);
    const body = containerActionSchema.parse(request.body);
    
    try {
      switch (body.action) {
        case 'start':
          await dockerService.startContainer(params.id);
          break;
        case 'stop':
          await dockerService.stopContainer(params.id);
          break;
        case 'restart':
          await dockerService.restartContainer(params.id);
          break;
      }
      
      reply.send({
        success: true,
        message: `Container ${body.action}ed successfully`,
      });
    } catch (error) {
      logger.error(`Failed to ${body.action} container ${params.id}:`, error);
      reply.code(500).send({ error: `Failed to ${body.action} container` });
    }
  });

  /**
   * @GET /api/docker/system
   * @description Get Docker system information
   */
  fastify.get('/api/docker/system', {
    schema: {
      tags: ['Docker'],
      summary: 'Docker system info',
      description: 'Retrieve Docker system information',
      response: {
        200: {
          type: 'object',
          properties: {
            containers: { type: 'number' },
            images: { type: 'number' },
            volumes: { type: 'number' },
            networks: { type: 'number' },
          },
        },
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    try {
      const systemInfo = await dockerService.getSystemInfo();
      reply.send(systemInfo);
    } catch (error) {
      logger.error('Failed to fetch Docker system info:', error);
      reply.code(500).send({ error: 'Failed to fetch Docker system info' });
    }
  });
}