/**
 * @file health.ts
 * @description Health check endpoints for service monitoring
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { checkDatabaseConnection } from '../db/client';
import { cacheService } from '../services/cache.service';
import { dockerService } from '../services/docker.service';
import { proxmoxService } from '../services/proxmox.service';

export default async function healthRoutes(fastify: FastifyInstance) {
  /**
   * @GET /health
   * @description Basic health check endpoint
   */
  fastify.get('/health', {
    schema: {
      tags: ['Health'],
      summary: 'Basic health check',
      description: 'Returns the current health status of the API',
      response: {
        200: {
          type: 'object',
          properties: {
            status: { type: 'string' },
            timestamp: { type: 'string' },
            uptime: { type: 'number' },
            version: { type: 'string' },
          },
        },
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    const uptime = process.uptime();
    const version = process.env.npm_package_version || '1.0.0';

    reply.send({
      status: 'healthy',
      timestamp: new Date().toISOString(),
      uptime: Math.round(uptime),
      version,
    });
  });

  /**
   * @GET /health/detailed
   * @description Detailed health check with service dependencies
   */
  fastify.get('/health/detailed', {
    schema: {
      tags: ['Health'],
      summary: 'Detailed health check',
      description: 'Returns detailed health status of all services',
      response: {
        200: {
          type: 'object',
          properties: {
            status: { type: 'string' },
            timestamp: { type: 'string' },
            services: {
              type: 'object',
              properties: {
                database: {
                  type: 'object',
                  properties: {
                    status: { type: 'string' },
                    latency: { type: 'number' },
                  },
                },
                redis: {
                  type: 'object',
                  properties: {
                    status: { type: 'string' },
                    latency: { type: 'number' },
                  },
                },
                docker: {
                  type: 'object',
                  properties: {
                    status: { type: 'string' },
                  },
                },
                proxmox: {
                  type: 'object',
                  properties: {
                    status: { type: 'string' },
                  },
                },
              },
            },
          },
        },
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    const startTime = Date.now();
    const services: any = {};

    // Check database
    const dbStart = Date.now();
    const dbHealthy = await checkDatabaseConnection();
    services.database = {
      status: dbHealthy ? 'healthy' : 'unhealthy',
      latency: Date.now() - dbStart,
    };

    // Check Redis
    const redisStart = Date.now();
    try {
      await cacheService.exists('health:check');
      services.redis = {
        status: 'healthy',
        latency: Date.now() - redisStart,
      };
    } catch (error) {
      services.redis = {
        status: 'unhealthy',
        latency: Date.now() - redisStart,
      };
    }

    // Check Docker
    try {
      await dockerService.listContainers();
      services.docker = { status: 'healthy' };
    } catch (error) {
      services.docker = { status: 'unhealthy' };
    }

    // Check Proxmox
    if (proxmoxService.isConfigured()) {
      try {
        await proxmoxService.getNodes();
        services.proxmox = { status: 'healthy' };
      } catch (error) {
        services.proxmox = { status: 'unhealthy' };
      }
    } else {
      services.proxmox = { status: 'not_configured' };
    }

    const allHealthy = Object.values(services).every(
      (service: any) => service.status === 'healthy' || service.status === 'not_configured'
    );

    reply.send({
      status: allHealthy ? 'healthy' : 'degraded',
      timestamp: new Date().toISOString(),
      services,
    });
  });
}