/**
 * @file notes.ts
 * @description Notes CRUD endpoints
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { z } from 'zod';
import { db } from '../db/client';
import { notes, insertNoteSchema, selectNoteSchema } from '../db/schema';
import { eq } from 'drizzle-orm';
import { logger } from '../utils/logger';

const noteParamsSchema = z.object({
  id: z.string().uuid(),
});

export default async function notesRoutes(fastify: FastifyInstance) {
  /**
   * @GET /api/notes
   * @description Get all notes
   */
  fastify.get('/api/notes', {
    schema: {
      tags: ['Notes'],
      summary: 'List notes',
      description: 'Retrieve all notes',
      response: {
        200: {
          type: 'array',
          items: selectNoteSchema,
        },
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    try {
      const noteList = await db.select().from(notes).orderBy(notes.updatedAt);
      reply.send(noteList);
    } catch (error) {
      logger.error('Failed to fetch notes:', error);
      reply.code(500).send({ error: 'Failed to fetch notes' });
    }
  });

  /**
   * @POST /api/notes
   * @description Create a new note
   */
  fastify.post('/api/notes', {
    schema: {
      tags: ['Notes'],
      summary: 'Create note',
      description: 'Create a new note',
      body: insertNoteSchema,
      response: {
        201: selectNoteSchema,
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    const noteData = insertNoteSchema.parse(request.body);
    
    try {
      const [newNote] = await db.insert(notes).values(noteData).returning();
      logger.info(`Note created: ${newNote.id}`);
      reply.code(201).send(newNote);
    } catch (error) {
      logger.error('Failed to create note:', error);
      reply.code(500).send({ error: 'Failed to create note' });
    }
  });

  /**
   * @GET /api/notes/:id
   * @description Get a specific note by ID
   */
  fastify.get('/api/notes/:id', {
    schema: {
      tags: ['Notes'],
      summary: 'Get note',
      description: 'Retrieve a specific note by ID',
      params: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
        },
        required: ['id'],
      },
      response: {
        200: selectNoteSchema,
        404: {
          type: 'object',
          properties: {
            error: { type: 'string' },
          },
        },
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    const params = noteParamsSchema.parse(request.params);
    
    try {
      const [note] = await db.select().from(notes).where(eq(notes.id, params.id));
      
      if (!note) {
        reply.code(404).send({ error: 'Note not found' });
        return;
      }
      
      reply.send(note);
    } catch (error) {
      logger.error(`Failed to fetch note ${params.id}:`, error);
      reply.code(500).send({ error: 'Failed to fetch note' });
    }
  });

  /**
   * @PUT /api/notes/:id
   * @description Update a note
   */
  fastify.put('/api/notes/:id', {
    schema: {
      tags: ['Notes'],
      summary: 'Update note',
      description: 'Update an existing note',
      params: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
        },
        required: ['id'],
      },
      body: insertNoteSchema.partial(),
      response: {
        200: selectNoteSchema,
        404: {
          type: 'object',
          properties: {
            error: { type: 'string' },
          },
        },
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    const params = noteParamsSchema.parse(request.params);
    const updateData = insertNoteSchema.partial().parse(request.body);
    
    try {
      const [updatedNote] = await db
        .update(notes)
        .set({ ...updateData, updatedAt: new Date() })
        .where(eq(notes.id, params.id))
        .returning();
      
      if (!updatedNote) {
        reply.code(404).send({ error: 'Note not found' });
        return;
      }
      
      logger.info(`Note updated: ${params.id}`);
      reply.send(updatedNote);
    } catch (error) {
      logger.error(`Failed to update note ${params.id}:`, error);
      reply.code(500).send({ error: 'Failed to update note' });
    }
  });

  /**
   * @DELETE /api/notes/:id
   * @description Delete a note
   */
  fastify.delete('/api/notes/:id', {
    schema: {
      tags: ['Notes'],
      summary: 'Delete note',
      description: 'Delete a note',
      params: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
        },
        required: ['id'],
      },
      response: {
        204: {
          type: 'null',
          description: 'Note deleted successfully',
        },
        404: {
          type: 'object',
          properties: {
            error: { type: 'string' },
          },
        },
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    const params = noteParamsSchema.parse(request.params);
    
    try {
      const [deletedNote] = await db.delete(notes).where(eq(notes.id, params.id)).returning();
      
      if (!deletedNote) {
        reply.code(404).send({ error: 'Note not found' });
        return;
      }
      
      logger.info(`Note deleted: ${params.id}`);
      reply.code(204).send();
    } catch (error) {
      logger.error(`Failed to delete note ${params.id}:`, error);
      reply.code(500).send({ error: 'Failed to delete note' });
    }
  });
}