/**
 * @file proxmox.ts
 * @description Proxmox VE API proxy endpoints
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { z } from 'zod';
import { proxmoxService } from '../services/proxmox.service';
import { logger } from '../utils/logger';

const vmActionSchema = z.object({
  action: z.enum(['start', 'stop']),
});

export default async function proxmoxRoutes(fastify: FastifyInstance) {
  // Check if Proxmox is configured
  if (!proxmoxService.isConfigured()) {
    fastify.log.warn('Proxmox service not configured, skipping routes');
    return;
  }

  /**
   * @GET /api/proxmox/nodes
   * @description Get Proxmox nodes
   */
  fastify.get('/api/proxmox/nodes', {
    schema: {
      tags: ['Proxmox'],
      summary: 'List nodes',
      description: 'Retrieve all Proxmox VE nodes',
      response: {
        200: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              node: { type: 'string' },
              status: { type: 'string' },
              cpu: { type: 'number' },
              maxcpu: { type: 'number' },
              mem: { type: 'number' },
              maxmem: { type: 'number' },
              disk: { type: 'number' },
              maxdisk: { type: 'number' },
            },
          },
        },
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    try {
      const nodes = await proxmoxService.getNodes();
      reply.send(nodes);
    } catch (error) {
      logger.error('Failed to fetch Proxmox nodes:', error);
      reply.code(500).send({ error: 'Failed to fetch Proxmox nodes' });
    }
  });

  /**
   * @GET /api/proxmox/nodes/:node/vms
   * @description Get VMs and containers for a specific node
   */
  fastify.get('/api/proxmox/nodes/:node/vms', {
    schema: {
      tags: ['Proxmox'],
      summary: 'List VMs',
      description: 'Retrieve VMs and containers for a node',
      params: {
        type: 'object',
        properties: {
          node: { type: 'string' },
        },
        required: ['node'],
      },
      response: {
        200: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              vmid: { type: 'number' },
              name: { type: 'string' },
              status: { type: 'string' },
              cpu: { type: 'number' },
              maxcpu: { type: 'number' },
              mem: { type: 'number' },
              maxmem: { type: 'number' },
              disk: { type: 'number' },
              maxdisk: { type: 'number' },
              type: { type: 'string', enum: ['qemu', 'lxc'] },
            },
          },
        },
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    const params = z.object({ node: z.string() }).parse(request.params);
    
    try {
      const vms = await proxmoxService.getVMs(params.node);
      reply.send(vms);
    } catch (error) {
      logger.error(`Failed to fetch VMs for node ${params.node}:`, error);
      reply.code(500).send({ error: 'Failed to fetch VMs' });
    }
  });

  /**
   * @GET /api/proxmox/nodes/:node/storage
   * @description Get storage information for a node
   */
  fastify.get('/api/proxmox/nodes/:node/storage', {
    schema: {
      tags: ['Proxmox'],
      summary: 'List storage',
      description: 'Retrieve storage information for a node',
      params: {
        type: 'object',
        properties: {
          node: { type: 'string' },
        },
        required: ['node'],
      },
      response: {
        200: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              storage: { type: 'string' },
              type: { type: 'string' },
              content: { type: 'string' },
              used: { type: 'number' },
              total: { type: 'number' },
              available: { type: 'number' },
            },
          },
        },
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    const params = z.object({ node: z.string() }).parse(request.params);
    
    try {
      const storage = await proxmoxService.getStorage(params.node);
      reply.send(storage);
    } catch (error) {
      logger.error(`Failed to fetch storage for node ${params.node}:`, error);
      reply.code(500).send({ error: 'Failed to fetch storage' });
    }
  });

  /**
   * @POST /api/proxmox/nodes/:node/vms/:vmid/action
   * @description Perform action on VM (start/stop)
   */
  fastify.post('/api/proxmox/nodes/:node/vms/:vmid/action', {
    schema: {
      tags: ['Proxmox'],
      summary: 'VM action',
      description: 'Perform action on VM or container',
      params: {
        type: 'object',
        properties: {
          node: { type: 'string' },
          vmid: { type: 'number' },
        },
        required: ['node', 'vmid'],
      },
      body: {
        type: 'object',
        properties: {
          action: { type: 'string', enum: ['start', 'stop'] },
          type: { type: 'string', enum: ['qemu', 'lxc'] },
        },
        required: ['action', 'type'],
      },
      response: {
        200: {
          type: 'object',
          properties: {
            success: { type: 'boolean' },
            message: { type: 'string' },
          },
        },
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    const params = z.object({ 
      node: z.string(),
      vmid: z.coerce.number(),
    }).parse(request.params);
    
    const body = z.object({
      action: z.enum(['start', 'stop']),
      type: z.enum(['qemu', 'lxc']),
    }).parse(request.body);
    
    try {
      switch (body.action) {
        case 'start':
          await proxmoxService.startVM(params.node, params.vmid, body.type);
          break;
        case 'stop':
          await proxmoxService.stopVM(params.node, params.vmid, body.type);
          break;
      }
      
      reply.send({
        success: true,
        message: `${body.type.toUpperCase()} ${params.vmid} ${body.action}ed successfully`,
      });
    } catch (error) {
      logger.error(`Failed to ${body.action} VM ${params.vmid}:`, error);
      reply.code(500).send({ error: `Failed to ${body.action} VM` });
    }
  });

  /**
   * @GET /api/proxmox/cluster
   * @description Get cluster status
   */
  fastify.get('/api/proxmox/cluster', {
    schema: {
      tags: ['Proxmox'],
      summary: 'Cluster status',
      description: 'Retrieve Proxmox cluster status',
      response: {
        200: {
          type: 'object',
          properties: {
            cluster: { type: 'object' },
            quorum: { type: 'object' },
          },
        },
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    try {
      const status = await proxmoxService.getClusterStatus();
      reply.send(status);
    } catch (error) {
      logger.error('Failed to fetch cluster status:', error);
      reply.code(500).send({ error: 'Failed to fetch cluster status' });
    }
  });
}