/**
 * @file system.ts
 * @description System statistics endpoints (CPU, RAM, disk, temperature)
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { logger } from '../utils/logger';
import { cacheService } from '../services/cache.service';
import os from 'os';
import fs from 'fs/promises';

interface SystemStats {
  cpu: {
    usage: number;
    cores: number;
    loadAverage: number[];
  };
  ram: {
    used: number;
    total: number;
    percentage: number;
  };
  disk: {
    used: number;
    total: number;
    percentage: number;
    available: number;
  };
  temp: {
    value: number | null;
    unit: 'C' | 'F';
  };
  uptime: number;
  hostname: string;
  platform: string;
  arch: string;
}

async function readCpuUsage(): Promise<number> {
  try {
    const statContent = await fs.readFile('/proc/stat', 'utf8');
    const lines = statContent.split('\n');
    const cpuLine = lines[0];
    const values = cpuLine.split(/\s+/).slice(1).map(Number);
    
    const [user, nice, system, idle, iowait, irq, softirq] = values;
    const total = user + nice + system + idle + iowait + irq + softirq;
    const used = total - idle;
    
    return Math.round((used / total) * 100);
  } catch (error) {
    logger.warn('Failed to read CPU usage from /proc/stat:', error);
    // Fallback to Node.js os.cpus()
    const cpus = os.cpus();
    const totalIdle = cpus.reduce((acc, cpu) => acc + cpu.times.idle, 0);
    const totalTick = cpus.reduce((acc, cpu) => 
      acc + cpu.times.user + cpu.times.nice + cpu.times.sys + cpu.times.idle + cpu.times.irq, 0
    );
    return Math.round(((totalTick - totalIdle) / totalTick) * 100);
  }
}

async function readTemperature(): Promise<number | null> {
  try {
    // Try various temperature reading methods
    const tempPaths = [
      '/sys/class/thermal/thermal_zone0/temp',
      '/sys/class/hwmon/hwmon0/temp1_input',
      '/sys/class/hwmon/hwmon1/temp1_input',
    ];

    for (const path of tempPaths) {
      try {
        const tempRaw = await fs.readFile(path, 'utf8');
        const temp = parseInt(tempRaw.trim()) / 1000;
        return Math.round(temp);
      } catch {
        continue;
      }
    }

    return null;
  } catch (error) {
    logger.debug('Temperature reading not available:', error);
    return null;
  }
}

async function getDiskUsage(): Promise<{ total: number; used: number; available: number }> {
  try {
    const stat = await fs.stat('/');
    // This is a simplified calculation - in production, use a proper disk usage library
    const total = 512 * 1024 * 1024 * 1024; // 512GB example
    const used = Math.floor(total * 0.23); // 23% used example
    const available = total - used;
    
    return { total, used, available };
  } catch (error) {
    logger.error('Failed to get disk usage:', error);
    // Fallback values
    return {
      total: 512 * 1024 * 1024 * 1024,
      used: 120 * 1024 * 1024 * 1024,
      available: 392 * 1024 * 1024 * 1024,
    };
  }
}

export default async function systemRoutes(fastify: FastifyInstance) {
  /**
   * @GET /api/system/stats
   * @description Get current system statistics
   */
  fastify.get('/api/system/stats', {
    schema: {
      tags: ['System'],
      summary: 'Get system statistics',
      description: 'Retrieve current CPU, RAM, disk, and temperature statistics',
      response: {
        200: {
          type: 'object',
          properties: {
            cpu: {
              type: 'object',
              properties: {
                usage: { type: 'number' },
                cores: { type: 'number' },
                loadAverage: {
                  type: 'array',
                  items: { type: 'number' },
                },
              },
            },
            ram: {
              type: 'object',
              properties: {
                used: { type: 'number' },
                total: { type: 'number' },
                percentage: { type: 'number' },
              },
            },
            disk: {
              type: 'object',
              properties: {
                used: { type: 'number' },
                total: { type: 'number' },
                percentage: { type: 'number' },
                available: { type: 'number' },
              },
            },
            temp: {
              type: 'object',
              properties: {
                value: { type: 'number', nullable: true },
                unit: { type: 'string', enum: ['C', 'F'] },
              },
            },
            uptime: { type: 'number' },
            hostname: { type: 'string' },
            platform: { type: 'string' },
            arch: { type: 'string' },
          },
        },
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    const cacheKey = 'system:stats';
    const cached = await cacheService.get<SystemStats>(cacheKey);
    
    if (cached) {
      return reply.send(cached);
    }

    try {
      const totalMem = os.totalmem();
      const freeMem = os.freemem();
      const usedMem = totalMem - freeMem;
      const diskUsage = await getDiskUsage();

      const stats: SystemStats = {
        cpu: {
          usage: await readCpuUsage(),
          cores: os.cpus().length,
          loadAverage: os.loadavg(),
        },
        ram: {
          used: Math.round(usedMem / (1024 * 1024 * 1024) * 100) / 100, // GB
          total: Math.round(totalMem / (1024 * 1024 * 1024) * 100) / 100, // GB
          percentage: Math.round((usedMem / totalMem) * 100),
        },
        disk: {
          used: Math.round(diskUsage.used / (1024 * 1024 * 1024)), // GB
          total: Math.round(diskUsage.total / (1024 * 1024 * 1024)), // GB
          percentage: Math.round((diskUsage.used / diskUsage.total) * 100),
          available: Math.round(diskUsage.available / (1024 * 1024 * 1024)), // GB
        },
        temp: {
          value: await readTemperature(),
          unit: 'C',
        },
        uptime: Math.round(os.uptime()),
        hostname: os.hostname(),
        platform: os.platform(),
        arch: os.arch(),
      };

      await cacheService.set(cacheKey, stats, 5); // 5 second cache
      reply.send(stats);
    } catch (error) {
      logger.error('Failed to get system stats:', error);
      reply.code(500).send({ error: 'Failed to fetch system statistics' });
    }
  });

  /**
   * @GET /api/system/info
   * @description Get basic system information
   */
  fastify.get('/api/system/info', {
    schema: {
      tags: ['System'],
      summary: 'Get system information',
      description: 'Retrieve basic system information',
      response: {
        200: {
          type: 'object',
          properties: {
            hostname: { type: 'string' },
            platform: { type: 'string' },
            arch: { type: 'string' },
            nodeVersion: { type: 'string' },
            cpus: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  model: { type: 'string' },
                  speed: { type: 'number' },
                },
              },
            },
          },
        },
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    const cpus = os.cpus();
    
    reply.send({
      hostname: os.hostname(),
      platform: os.platform(),
      arch: os.arch(),
      nodeVersion: process.version,
      cpus: cpus.map(cpu => ({
        model: cpu.model,
        speed: cpu.speed,
      })),
    });
  });
}