/**
 * @file weather.ts
 * @description OpenWeatherMap API proxy endpoints
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import axios from 'axios';
import { cacheService } from '../services/cache.service';
import { logger } from '../utils/logger';

interface WeatherData {
  temperature: number;
  feelsLike: number;
  description: string;
  icon: string;
  humidity: number;
  pressure: number;
  windSpeed: number;
  city: string;
  country: string;
  sunrise: number;
  sunset: number;
}

class WeatherService {
  private apiKey: string;
  private city: string;
  private api: any;

  constructor() {
    this.apiKey = process.env.OPENWEATHER_API_KEY || '';
    this.city = process.env.OPENWEATHER_CITY || 'Warsaw';

    if (this.apiKey) {
      this.api = axios.create({
        baseURL: 'https://api.openweathermap.org/data/2.5',
        timeout: 5000,
      });
    }
  }

  async getCurrentWeather(): Promise<WeatherData> {
    const cacheKey = `weather:${this.city}`;
    const cached = await cacheService.get<WeatherData>(cacheKey);
    
    if (cached) {
      return cached;
    }

    if (!this.apiKey) {
      // Return mock data for development
      const mockData: WeatherData = {
        temperature: 15,
        feelsLike: 13,
        description: 'partly cloudy',
        icon: '02d',
        humidity: 65,
        pressure: 1013,
        windSpeed: 3.5,
        city: this.city,
        country: 'PL',
        sunrise: Date.now() / 1000 - 3600,
        sunset: Date.now() / 1000 + 3600 * 8,
      };
      
      await cacheService.set(cacheKey, mockData, 300); // 5 minute cache
      return mockData;
    }

    try {
      const response = await this.api.get('/weather', {
        params: {
          q: this.city,
          appid: this.apiKey,
          units: 'metric',
          lang: 'pl',
        },
      });

      const data = response.data;
      const weatherData: WeatherData = {
        temperature: Math.round(data.main.temp * 10) / 10,
        feelsLike: Math.round(data.main.feels_like * 10) / 10,
        description: data.weather[0].description,
        icon: data.weather[0].icon,
        humidity: data.main.humidity,
        pressure: data.main.pressure,
        windSpeed: data.wind?.speed || 0,
        city: data.name,
        country: data.sys.country,
        sunrise: data.sys.sunrise,
        sunset: data.sys.sunset,
      };

      await cacheService.set(cacheKey, weatherData, 300); // 5 minute cache
      return weatherData;
    } catch (error) {
      logger.error('Failed to fetch weather data:', error);
      throw new Error('Failed to fetch weather data');
    }
  }

  isConfigured(): boolean {
    return !!(this.apiKey);
  }
}

const weatherService = new WeatherService();

export default async function weatherRoutes(fastify: FastifyInstance) {
  /**
   * @GET /api/weather
   * @description Get current weather
   */
  fastify.get('/api/weather', {
    schema: {
      tags: ['Weather'],
      summary: 'Get current weather',
      description: 'Retrieve current weather information',
      response: {
        200: {
          type: 'object',
          properties: {
            temperature: { type: 'number' },
            feelsLike: { type: 'number' },
            description: { type: 'string' },
            icon: { type: 'string' },
            humidity: { type: 'number' },
            pressure: { type: 'number' },
            windSpeed: { type: 'number' },
            city: { type: 'string' },
            country: { type: 'string' },
            sunrise: { type: 'number' },
            sunset: { type: 'number' },
          },
        },
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    try {
      const weather = await weatherService.getCurrentWeather();
      reply.send(weather);
    } catch (error) {
      logger.error('Failed to fetch weather:', error);
      reply.code(500).send({ error: 'Failed to fetch weather data' });
    }
  });

  /**
   * @GET /api/weather/configured
   * @description Check if weather service is configured
   */
  fastify.get('/api/weather/configured', {
    schema: {
      tags: ['Weather'],
      summary: 'Check weather configuration',
      description: 'Check if weather service is configured',
      response: {
        200: {
          type: 'object',
          properties: {
            configured: { type: 'boolean' },
            city: { type: 'string' },
          },
        },
      },
    },
  }, async (request: FastifyRequest, reply: FastifyReply) => {
    reply.send({
      configured: weatherService.isConfigured(),
      city: process.env.OPENWEATHER_CITY || 'Warsaw',
    });
  });
}