/**
 * @file editMode.ts
 * @description Edit mode state management store
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

import { writable } from 'svelte/store';
import { browser } from '$app/environment';

const STORAGE_KEY = 'dashboard-edit-mode';

// Get initial state from localStorage
const getInitialState = (): boolean => {
  if (!browser) return false;
  
  const stored = localStorage.getItem(STORAGE_KEY);
  return stored ? JSON.parse(stored) : false;
};

// Create the edit mode store
export const editMode = writable<boolean>(getInitialState());

// Update localStorage when store changes
editMode.subscribe((value) => {
  if (!browser) return;
  localStorage.setItem(STORAGE_KEY, JSON.stringify(value));
});

// Toggle edit mode
export const toggleEditMode = () => {
  editMode.update(current => !current);
};

// Enable edit mode
export const enableEditMode = () => {
  editMode.set(true);
};

// Disable edit mode
export const disableEditMode = () => {
  editMode.set(false);
};