/**
 * @file sidebar.ts
 * @description Sidebar state management store
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

import { writable } from 'svelte/store';
import { browser } from '$app/environment';

const STORAGE_KEY = 'dashboard-sidebar';

// Get initial state from localStorage
const getInitialState = (): boolean => {
  if (!browser) return false;
  
  const stored = localStorage.getItem(STORAGE_KEY);
  return stored ? JSON.parse(stored) : false;
};

// Create the sidebar store
export const sidebarOpen = writable<boolean>(getInitialState());

// Update localStorage when store changes
sidebarOpen.subscribe((value) => {
  if (!browser) return;
  localStorage.setItem(STORAGE_KEY, JSON.stringify(value));
});

// Toggle sidebar
export const toggleSidebar = () => {
  sidebarOpen.update(current => !current);
};

// Open sidebar
export const openSidebar = () => {
  sidebarOpen.set(true);
};

// Close sidebar
export const closeSidebar = () => {
  sidebarOpen.set(false);
};