/**
 * @file theme.ts
 * @description Theme management store
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

import { writable } from 'svelte/store';
import { browser } from '$app/environment';

export type Theme = 'blue' | 'orange' | 'purple';

const STORAGE_KEY = 'dashboard-theme';

// Get initial theme from localStorage or default to blue
const getInitialTheme = (): Theme => {
  if (!browser) return 'blue';
  
  const stored = localStorage.getItem(STORAGE_KEY) as Theme;
  return ['blue', 'orange', 'purple'].includes(stored) ? stored : 'blue';
};

// Create the theme store
export const theme = writable<Theme>(getInitialTheme());

// Update document theme attribute when store changes
theme.subscribe((value) => {
  if (!browser) return;
  
  document.documentElement.setAttribute('data-theme', value);
  localStorage.setItem(STORAGE_KEY, value);
});

// Theme switching function
export const setTheme = (newTheme: Theme) => {
  theme.set(newTheme);
};

// Toggle between themes
export const toggleTheme = () => {
  theme.update(current => {
    const themes: Theme[] = ['blue', 'orange', 'purple'];
    const currentIndex = themes.indexOf(current);
    const nextIndex = (currentIndex + 1) % themes.length;
    return themes[nextIndex];
  });
};