/**
 * @file widgets.ts
 * @description Widget state management store
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

import { writable, type Writable } from 'svelte/store';
import type { Widget } from '$lib/api/client';

// Widget store
export const widgets: Writable<Widget[]> = writable([]);

// Loading state
export const widgetsLoading = writable(true);

// Error state
export const widgetsError = writable<string | null>(null);

// Add widget to store
export const addWidget = (widget: Widget) => {
  widgets.update(current => [...current, widget]);
};

// Update widget in store
export const updateWidget = (id: string, updates: Partial<Widget>) => {
  widgets.update(current => 
    current.map(widget => 
      widget.id === id ? { ...widget, ...updates } : widget
    )
  );
};

// Remove widget from store
export const removeWidget = (id: string) => {
  widgets.update(current => current.filter(widget => widget.id !== id));
};

// Set all widgets
export const setWidgets = (widgetList: Widget[]) => {
  widgets.set(widgetList);
};

// Clear all widgets
export const clearWidgets = () => {
  widgets.set([]);
};