<!--
  @file CircularProgress.svelte
  @description Circular progress indicator component
  @author Generated by OK Computer for Michal's Dashboard
  @date 2025-01-07
-->

<script lang="ts">
  export let value: number;
  export let max: number = 100;
  export let size: number = 60;
  export let strokeWidth: number = 6;
  export let color: string = 'var(--accent-primary)';
  export let backgroundColor: string = 'var(--bg-secondary)';

  $: percentage = Math.min((value / max) * 100, 100);
  $: radius = (size - strokeWidth) / 2;
  $: circumference = 2 * Math.PI * radius;
  $: strokeDasharray = circumference;
  $: strokeDashoffset = circumference - (percentage / 100) * circumference;
</script>

<div class="circular-progress" style="width: {size}px; height: {size}px;">
  <svg class="progress-ring" width={size} height={size}>
    <!-- Background circle -->
    <circle
      class="progress-ring-background"
      stroke={backgroundColor}
      stroke-width={strokeWidth}
      fill="transparent"
      r={radius}
      cx={size / 2}
      cy={size / 2}
    />
    <!-- Progress circle -->
    <circle
      class="progress-ring-circle"
      stroke={color}
      stroke-width={strokeWidth}
      stroke-linecap="round"
      fill="transparent"
      r={radius}
      cx={size / 2}
      cy={size / 2}
      style="stroke-dasharray: {strokeDasharray}; stroke-dashoffset: {strokeDashoffset};"
    />
  </svg>
  <div class="progress-text">
    <slot>{Math.round(percentage)}%</slot>
  </div>
</div>

<style>
  .circular-progress {
    position: relative;
    display: inline-flex;
    align-items: center;
    justify-content: center;
  }

  .progress-ring {
    transform: rotate(-90deg);
  }

  .progress-ring-background {
    opacity: 0.3;
  }

  .progress-ring-circle {
    transition: stroke-dashoffset 0.5s ease-in-out;
    filter: drop-shadow(0 0 4px currentColor);
  }

  .progress-text {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: 0.875rem;
    font-weight: 600;
    color: var(--text-primary);
    text-align: center;
  }
</style>