/**
 * @file constants.ts
 * @description Shared constants for the dashboard
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

// Widget types
export const WIDGET_TYPES = {
  SYSTEM_STATS: 'system-stats',
  DOCKER_QUICK: 'docker-quick',
  PIHOLE_STATS: 'pihole-stats',
  QBITTORRENT_STATS: 'qbittorrent-stats',
  NOTES: 'notes',
} as const;

// Theme options
export const THEMES = {
  BLUE: 'blue',
  ORANGE: 'orange',
  PURPLE: 'purple',
} as const;

// Local storage keys
export const STORAGE_KEYS = {
  THEME: 'dashboard-theme',
  SIDEBAR: 'dashboard-sidebar',
  WIDGETS: 'dashboard-widgets',
  AUTH_TOKEN: 'dashboard-auth-token',
} as const;

// Cache TTL in seconds
export const CACHE_TTL = {
  SYSTEM_STATS: 5,
  DOCKER_CONTAINERS: 30,
  PIHOLE_STATS: 60,
  QBITTORRENT_STATS: 30,
  WEATHER: 300,
  PROXMOX: 60,
} as const;

// API endpoints
export const API_ENDPOINTS = {
  HEALTH: '/health',
  HEALTH_DETAILED: '/health/detailed',
  WIDGETS: '/api/widgets',
  SYSTEM_STATS: '/api/system/stats',
  DOCKER_CONTAINERS: '/api/docker/containers',
  PIHOLE_STATS: '/api/pihole/stats',
  QBITTORRENT_STATS: '/api/qbittorrent/stats',
  WEATHER: '/api/weather',
  NOTES: '/api/notes',
} as const;

// Error messages
export const ERROR_MESSAGES = {
  NETWORK_ERROR: 'Network error occurred',
  AUTH_ERROR: 'Authentication failed',
  NOT_FOUND: 'Resource not found',
  SERVER_ERROR: 'Server error occurred',
  VALIDATION_ERROR: 'Validation failed',
} as const;