/**
 * @file index.ts
 * @description Main export file for shared package
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

export * from './constants';

// Export generated types (will be created by openapi-typescript)
export * from './types/api';