/**
 * @file server.ts
 * @description Fastify server entry point
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

import { config } from 'dotenv';
import { resolve } from 'path';

config({ path: resolve(__dirname, '../.env') });

import Fastify from 'fastify';
import { logger, requestLogger } from './utils/logger';
import { checkDatabaseConnection } from './db/client';
import { cacheService } from './services/cache.service';
import { serializerCompiler, validatorCompiler, ZodTypeProvider } from 'fastify-type-provider-zod';
// Import plugins
import corsPlugin from './plugins/cors';
import swaggerPlugin from './plugins/swagger';
import authPlugin from './plugins/auth';

// Import routes
import healthRoutes from './routes/health';
import widgetRoutes from './routes/widgets';
import systemRoutes from './routes/system';
import dockerRoutes from './routes/docker';
import proxmoxRoutes from './routes/proxmox';
import piholeRoutes from './routes/pihole';
import qbittorrentRoutes from './routes/qbittorrent';
import weatherRoutes from './routes/weather';
import notesRoutes from './routes/notes';

const fastify = Fastify({
  logger: requestLogger,
  trustProxy: true,
}).withTypeProvider<ZodTypeProvider>();

// Dodaj przed pluginami
fastify.setValidatorCompiler(validatorCompiler);
fastify.setSerializerCompiler(serializerCompiler);

const port = parseInt(process.env.PORT || '3000');
const host = process.env.NODE_ENV === 'production' ? '0.0.0.0' : 'localhost';

async function startServer() {
  try {
    console.log('Registering plugins...');
    await fastify.register(corsPlugin);
    console.log('✓ CORS registered');
    
    await fastify.register(swaggerPlugin);
    console.log('✓ Swagger registered');
    
    await fastify.register(authPlugin);
    console.log('✓ Auth registered');
    
    console.log('Registering routes...');
    await fastify.register(healthRoutes);
    console.log('✓ Health routes registered');
    
    // Register routes
    await fastify.register(widgetRoutes, { prefix: '/api' });
    await fastify.register(systemRoutes, { prefix: '/api' });
    await fastify.register(dockerRoutes, { prefix: '/api' });
    await fastify.register(proxmoxRoutes, { prefix: '/api' });
    await fastify.register(piholeRoutes, { prefix: '/api' });
    await fastify.register(qbittorrentRoutes, { prefix: '/api' });
    await fastify.register(weatherRoutes, { prefix: '/api' });
    await fastify.register(notesRoutes, { prefix: '/api' });
    
    const dbHealthy = await checkDatabaseConnection();
    console.log('DB healthy:', dbHealthy);
    
    await fastify.listen({ port, host });
    console.log('✓ Server started on', host, port);
    
  } catch (error) {
    console.error('DETAILED ERROR:', error);
    logger.error('Failed to start server:', error);
    process.exit(1);
  }
}

// Graceful shutdown
process.on('SIGTERM', async () => {
  logger.info('SIGTERM received, shutting down gracefully...');
  await fastify.close();
  cacheService.disconnect();
  process.exit(0);
});

process.on('SIGINT', async () => {
  logger.info('SIGINT received, shutting down gracefully...');
  await fastify.close();
  cacheService.disconnect();
  process.exit(0);
});

// Start the server
startServer();