/**
 * @file server.ts
 * @description Fastify server entry point
 * @author Generated by OK Computer for Michal's Dashboard
 * @date 2025-01-07
 */

import Fastify from 'fastify';
import { logger, requestLogger } from './utils/logger';
import { checkDatabaseConnection } from './db/client';
import { cacheService } from './services/cache.service';

// Import plugins
import corsPlugin from './plugins/cors';
import swaggerPlugin from './plugins/swagger';
import authPlugin from './plugins/auth';

// Import routes
import healthRoutes from './routes/health';
import widgetRoutes from './routes/widgets';
import systemRoutes from './routes/system';
import dockerRoutes from './routes/docker';
import proxmoxRoutes from './routes/proxmox';
import piholeRoutes from './routes/pihole';
import qbittorrentRoutes from './routes/qbittorrent';
import weatherRoutes from './routes/weather';
import notesRoutes from './routes/notes';

const fastify = Fastify({
  logger: requestLogger,
  trustProxy: true,
});

const port = parseInt(process.env.PORT || '3000');
const host = process.env.NODE_ENV === 'production' ? '0.0.0.0' : 'localhost';

async function startServer() {
  try {
    // Register plugins
    await fastify.register(corsPlugin);
    await fastify.register(swaggerPlugin);
    await fastify.register(authPlugin);

    // Register routes
    await fastify.register(healthRoutes);
    await fastify.register(widgetRoutes);
    await fastify.register(systemRoutes);
    await fastify.register(dockerRoutes);
    await fastify.register(proxmoxRoutes);
    await fastify.register(piholeRoutes);
    await fastify.register(qbittorrentRoutes);
    await fastify.register(weatherRoutes);
    await fastify.register(notesRoutes);

    // Health check before starting
    const dbHealthy = await checkDatabaseConnection();
    if (!dbHealthy) {
      logger.error('Database connection failed, exiting...');
      process.exit(1);
    }

    logger.info('Database connection established');

    // Start server
    await fastify.listen({ port, host });
    logger.info(`Server listening on ${host}:${port}`);
    logger.info(`API documentation available at http://${host}:${port}/docs`);

  } catch (error) {
    logger.error('Failed to start server:', error);
    process.exit(1);
  }
}

// Graceful shutdown
process.on('SIGTERM', async () => {
  logger.info('SIGTERM received, shutting down gracefully...');
  await fastify.close();
  cacheService.disconnect();
  process.exit(0);
});

process.on('SIGINT', async () => {
  logger.info('SIGINT received, shutting down gracefully...');
  await fastify.close();
  cacheService.disconnect();
  process.exit(0);
});

// Start the server
startServer();