#!/bin/bash

# Start all development services
# @author Generated by OK Computer for Michal's Dashboard
# @date 2025-01-07

set -e

echo "Starting development environment..."

# Start PostgreSQL and Redis
echo "Starting databases..."
docker-compose -f docker-compose.dev.yml up -d

# Wait for databases to be ready
echo "Waiting for databases to be ready..."
sleep 5

# Run database migrations
echo "Running database migrations..."
pnpm --filter api db:migrate

# Start API and Web in parallel
echo "Starting API and Web servers..."
pnpm dev

echo "Development environment started!"
echo "- API: http://localhost:3000"
echo "- Web: http://localhost:5173"
echo "- API Docs: http://localhost:3000/docs"