#!/bin/bash

# Generate TypeScript and Dart clients from OpenAPI spec
# @author Generated by OK Computer for Michal's Dashboard
# @date 2025-01-07

set -e

echo "Generating API clients..."

# Ensure OpenAPI spec exists
if [ ! -f "openapi.json" ]; then
    echo "OpenAPI spec not found. Running generate-openapi.sh first..."
    ./scripts/generate-openapi.sh
fi

# Generate TypeScript client for web
echo "Generating TypeScript client..."
npx openapi-typescript openapi.json --output packages/shared/src/types/api.ts

# Generate Dart client for mobile
echo "Generating Dart client..."
npx @openapitools/openapi-generator-cli generate \
    -i openapi.json \
    -g dart \
    -o apps/mobile/lib/api \
    --additional-properties=pubName=dashboard_api_client

echo "API clients generated successfully!"
echo "- TypeScript client: packages/shared/src/types/api.ts"
echo "- Dart client: apps/mobile/lib/api/"