#!/bin/bash

# Generate OpenAPI specification from Fastify API
# @author Generated by OK Computer for Michal's Dashboard
# @date 2025-01-07

set -e

echo "Generating OpenAPI specification..."

# Start the API server in background
pnpm --filter api dev &
API_PID=$!

# Wait for server to start
sleep 5

# Fetch OpenAPI spec
curl -s http://localhost:3000/docs/json > openapi.json

# Stop the API server
kill $API_PID

echo "OpenAPI specification generated: openapi.json"