<!--
  @file +page.svelte
  @description Settings page with tabs for general, appearance, and keyboard shortcuts
  @author Generated by OK Computer for Michal's Dashboard
  @date 2025-01-07
-->

<script lang="ts">
  import { onMount } from 'svelte';
  import { Settings, Palette, Keyboard, Save, Globe, Search } from 'lucide-svelte';
  import { theme, setTheme, type Theme } from '$lib/stores/theme';
  import { fade } from 'svelte/transition';

  type Tab = 'general' | 'appearance' | 'shortcuts';

  let activeTab: Tab = 'general';
  let siteName = 'Dashboard';
  let language = 'pl';
  let enableSearch = true;
  let saveLoading = false;
  let saveSuccess = false;

  // Theme colors for customization
  const themeColors = {
    blue: {
      primary: '#00d4ff',
      secondary: 'rgba(0, 212, 255, 0.1)',
    },
    orange: {
      primary: '#ff6b35',
      secondary: 'rgba(255, 107, 53, 0.1)',
    },
    purple: {
      primary: '#9d4edd',
      secondary: 'rgba(157, 78, 221, 0.1)',
    },
  };

  let customColors = {
    primary: '#00d4ff',
    secondary: 'rgba(0, 212, 255, 0.1)',
  };

  const tabs = [
    { id: 'general', label: 'Ogólne', icon: Settings },
    { id: 'appearance', label: 'Wygląd', icon: Palette },
    { id: 'shortcuts', label: 'Skróty klawiszowe', icon: Keyboard },
  ];

  const languages = [
    { value: 'pl', label: 'Polski' },
    { value: 'en', label: 'English' },
    { value: 'de', label: 'Deutsch' },
  ];

  const themeOptions: { id: Theme; name: string; color: string }[] = [
    { id: 'blue', name: 'Niebieski', color: '#00d4ff' },
    { id: 'orange', name: 'Pomarańczowy', color: '#ff6b35' },
    { id: 'purple', name: 'Fioletowy', color: '#9d4edd' },
  ];

  const handleSave = async () => {
    saveLoading = true;
    
    try {
      // Save settings to localStorage (in production, save to API)
      localStorage.setItem('dashboard_settings', JSON.stringify({
        siteName,
        language,
        enableSearch,
        customColors,
      }));
      
      // Apply custom colors if different from theme
      if (customColors.primary !== themeColors[$theme].primary) {
        document.documentElement.style.setProperty('--accent-primary', customColors.primary);
      }
      
      saveSuccess = true;
      setTimeout(() => {
        saveSuccess = false;
      }, 3000);
    } catch (err) {
      console.error('Failed to save settings:', err);
    } finally {
      saveLoading = false;
    }
  };

  const loadSettings = () => {
    try {
      const saved = localStorage.getItem('dashboard_settings');
      if (saved) {
        const settings = JSON.parse(saved);
        siteName = settings.siteName || 'Dashboard';
        language = settings.language || 'pl';
        enableSearch = settings.enableSearch !== false;
        customColors = settings.customColors || themeColors[$theme];
      }
    } catch (err) {
      console.error('Failed to load settings:', err);
    }
  };

  const applyTheme = (newTheme: Theme) => {
    setTheme(newTheme);
    customColors = themeColors[newTheme];
  };

  onMount(() => {
    loadSettings();
  });

  $: currentTheme = $theme;
</script>

<svelte:head>
  <title>Ustawienia - Dashboard</title>
</svelte:head>

<div class="settings-page">
  <div class="settings-header">
    <div class="header-content">
      <Settings size={32} />
      <h1>Ustawienia</h1>
      <p>Dostosuj wygląd i zachowanie dashboardu</p>
    </div>
  </div>

  <!-- Tabs -->
  <div class="tabs-container">
    <nav class="tabs">
      {#each tabs as tab}
        <button
          class="tab"
          class:active={activeTab === tab.id}
          on:click={() => activeTab = tab.id}
        >
          <svelte:component this={tab.icon} size={18} />
          <span>{tab.label}</span>
        </button>
      {/each}
    </nav>
  </div>

  <!-- Tab Content -->
  <div class="tab-content">
    {#if activeTab === 'general'}
      <div class="general-settings" transition:fade>
        <div class="setting-section">
          <h3>Ogólne ustawienia</h3>
          
          <div class="setting-item">
            <label for="siteName">Nazwa strony</label>
            <input
              id="siteName"
              type="text"
              bind:value={siteName}
              placeholder="Dashboard"
            />
          </div>

          <div class="setting-item">
            <label for="language">Język</label>
            <select id="language" bind:value={language}>
              {#each languages as lang}
                <option value={lang.value}>{lang.label}</option>
              {/each}
            </select>
          </div>

          <div class="setting-item">
            <label class="toggle-label">
              <input
                type="checkbox"
                bind:checked={enableSearch}
              />
              <span class="toggle-slider"></span>
              Pokaż pasek wyszukiwania
            </label>
          </div>
        </div>
      </div>
    {:else if activeTab === 'appearance'}
      <div class="appearance-settings" transition:fade>
        <div class="setting-section">
          <h3>Motyw</h3>
          
          <div class="theme-selector">
            <p>Wybierz motyw:</p>
            <div class="theme-options">
              {#each themeOptions as { id, name, color }}
                <button
                  class="theme-option"
                  class:active={currentTheme === id}
                  on:click={() => applyTheme(id)}
                  style="--theme-color: {color}"
                >
                  <div class="theme-preview"></div>
                  <span>{name}</span>
                </button>
              {/each}
            </div>
          </div>
        </div>

        <div class="setting-section">
          <h3>Kolory niestandardowe</h3>
          
          <div class="color-customization">
            <div class="color-picker">
              <label for="primaryColor">Kolor główny</label>
              <input
                id="primaryColor"
                type="color"
                bind:value={customColors.primary}
              />
            </div>
            
            <div class="color-preview">
              <div 
                class="color-sample"
                style="background-color: {customColors.primary}"
              ></div>
              <span>Podgląd</span>
            </div>
          </div>
        </div>
      </div>
    {:else if activeTab === 'shortcuts'}
      <div class="shortcuts-settings" transition:fade>
        <div class="setting-section">
          <h3>Skróty klawiszowe</h3>
          
          <div class="shortcuts-list">
            <div class="shortcut-item">
              <span class="shortcut-action">Otwórz szukajkę</span>
              <kbd>Ctrl + K</kbd>
            </div>
            <div class="shortcut-item">
              <span class="shortcut-action">Przełącz pasek boczny</span>
              <kbd>Ctrl + B</kbd>
            </div>
            <div class="shortcut-item">
              <span class="shortcut-action">Dodaj widget</span>
              <kbd>Ctrl + N</kbd>
            </div>
            <div class="shortcut-item">
              <span class="shortcut-action">Ustawienia</span>
              <kbd>Ctrl + ,</kbd>
            </div>
          </div>
        </div>
      </div>
    {/if}
  </div>

  <!-- Save Button -->
  <div class="settings-footer">
    <button
      class="save-btn"
      on:click={handleSave}
      disabled={saveLoading}
    >
      {#if saveLoading}
        <div class="loading-spinner"></div>
        Zapisywanie...
      {:else if saveSuccess}
        ✓ Zapisano!
      {:else}
        <Save size={16} />
        Zapisz ustawienia
      {/if}
    </button>
  </div>
</div>

<style>
  .settings-page {
    max-width: 800px;
    margin: 0 auto;
    padding: 2rem;
    min-height: 100vh;
  }

  .settings-header {
    margin-bottom: 2rem;
    padding-bottom: 1rem;
    border-bottom: 1px solid var(--border);
  }

  .header-content {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    gap: 0.5rem;
  }

  .header-content :global(svg) {
    color: var(--accent-primary);
  }

  .header-content h1 {
    color: var(--text-primary);
    margin: 0;
  }

  .header-content p {
    color: var(--text-muted);
    margin: 0;
  }

  .tabs-container {
    margin-bottom: 2rem;
    border-bottom: 1px solid var(--border);
  }

  .tabs {
    display: flex;
    gap: 0.5rem;
  }

  .tab {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.75rem 1rem;
    background: none;
    border: none;
    color: var(--text-muted);
    cursor: pointer;
    border-bottom: 2px solid transparent;
    transition: all var(--transition-fast);
    font-size: 0.875rem;
  }

  .tab:hover {
    color: var(--text-primary);
    background-color: var(--bg-hover);
  }

  .tab.active {
    color: var(--accent-primary);
    border-bottom-color: var(--accent-primary);
    background-color: var(--accent-secondary);
  }

  .tab-content {
    min-height: 400px;
  }

  .setting-section {
    margin-bottom: 2rem;
  }

  .setting-section h3 {
    color: var(--text-primary);
    margin-bottom: 1rem;
    font-size: 1.125rem;
  }

  .setting-item {
    margin-bottom: 1.5rem;
  }

  .setting-item label {
    display: block;
    margin-bottom: 0.5rem;
    color: var(--text-secondary);
    font-weight: 500;
    font-size: 0.875rem;
  }

  .setting-item input,
  .setting-item select {
    width: 100%;
    max-width: 400px;
    padding: 0.75rem;
    background-color: var(--bg-secondary);
    border: 1px solid var(--border);
    border-radius: var(--radius-md);
    color: var(--text-primary);
    font-size: 0.875rem;
    transition: all var(--transition-fast);
  }

  .setting-item input:focus,
  .setting-item select:focus {
    outline: none;
    border-color: var(--accent-primary);
    box-shadow: 0 0 0 3px var(--accent-secondary);
  }

  .toggle-label {
    display: flex !important;
    align-items: center;
    gap: 0.75rem;
    cursor: pointer;
    user-select: none;
  }

  .toggle-label input {
    display: none;
  }

  .toggle-slider {
    position: relative;
    width: 44px;
    height: 24px;
    background-color: var(--border);
    border-radius: 12px;
    transition: all var(--transition-fast);
  }

  .toggle-slider::before {
    content: '';
    position: absolute;
    top: 2px;
    left: 2px;
    width: 20px;
    height: 20px;
    background-color: var(--bg-card);
    border-radius: 50%;
    transition: all var(--transition-fast);
  }

  .toggle-label input:checked + .toggle-slider {
    background-color: var(--accent-primary);
  }

  .toggle-label input:checked + .toggle-slider::before {
    transform: translateX(20px);
  }

  .theme-selector {
    margin-bottom: 2rem;
  }

  .theme-selector p {
    color: var(--text-secondary);
    margin-bottom: 1rem;
    font-size: 0.875rem;
  }

  .theme-options {
    display: flex;
    gap: 1rem;
  }

  .theme-option {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.5rem;
    padding: 1rem;
    background-color: var(--bg-secondary);
    border: 2px solid var(--border);
    border-radius: var(--radius-md);
    cursor: pointer;
    transition: all var(--transition-fast);
    min-width: 80px;
  }

  .theme-option:hover {
    border-color: var(--border-hover);
  }

  .theme-option.active {
    border-color: var(--theme-color);
    background-color: var(--theme-color) + '20';
  }

  .theme-preview {
    width: 40px;
    height: 40px;
    border-radius: 50%;
    background-color: var(--theme-color);
    box-shadow: 0 0 20px var(--theme-color);
  }

  .theme-option span {
    font-size: 0.75rem;
    color: var(--text-secondary);
  }

  .color-customization {
    display: flex;
    align-items: center;
    gap: 2rem;
  }

  .color-picker {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  .color-picker label {
    color: var(--text-secondary);
    font-size: 0.875rem;
    font-weight: 500;
  }

  .color-picker input {
    width: 60px;
    height: 40px;
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    cursor: pointer;
  }

  .color-preview {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.5rem;
  }

  .color-sample {
    width: 60px;
    height: 40px;
    border-radius: var(--radius-sm);
    border: 1px solid var(--border);
  }

  .color-preview span {
    font-size: 0.75rem;
    color: var(--text-muted);
  }

  .shortcuts-list {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .shortcut-item {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1rem;
    background-color: var(--bg-secondary);
    border: 1px solid var(--border);
    border-radius: var(--radius-md);
  }

  .shortcut-action {
    color: var(--text-primary);
    font-size: 0.875rem;
  }

  kbd {
    padding: 0.25rem 0.5rem;
    background-color: var(--bg-card);
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    font-family: 'JetBrains Mono', monospace;
    font-size: 0.75rem;
    color: var(--text-muted);
  }

  .settings-footer {
    margin-top: 2rem;
    padding-top: 1rem;
    border-top: 1px solid var(--border);
    display: flex;
    justify-content: flex-end;
  }

  .save-btn {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.75rem 1.5rem;
    background-color: var(--accent-primary);
    color: var(--bg-primary);
    border: none;
    border-radius: var(--radius-md);
    font-size: 0.875rem;
    font-weight: 500;
    cursor: pointer;
    transition: all var(--transition-fast);
  }

  .save-btn:hover:not(:disabled) {
    filter: brightness(1.1);
    transform: translateY(-1px);
  }

  .save-btn:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .loading-spinner {
    width: 16px;
    height: 16px;
    border: 2px solid transparent;
    border-top-color: currentColor;
    border-radius: 50%;
    animation: spin 1s linear infinite;
  }

  @keyframes spin {
    from { transform: rotate(0deg); }
    to { transform: rotate(360deg); }
  }

  @media (max-width: 640px) {
    .settings-page {
      padding: 1rem;
    }

    .theme-options {
      flex-direction: column;
    }

    .color-customization {
      flex-direction: column;
      align-items: flex-start;
      gap: 1rem;
    }

    .tabs {
      overflow-x: auto;
    }
  }
</style>