<!--
  @file WidgetWrapper.svelte
  @description Widget container with header, drag handle, and actions
  @author Generated by OK Computer for Michal's Dashboard
  @date 2025-01-07
-->

<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { GripVertical, Settings2, X } from 'lucide-svelte';
  import type { Widget } from '$lib/api/client';
  import { getWidgetDefinition } from '$lib/widgets/registry';

  export let widget: Widget;
  export let editable = true;
  export let loading = false;

  const dispatch = createEventDispatcher();

  $: definition = getWidgetDefinition(widget.type);
  $: widgetTitle = definition?.name || widget.type;

  const handleSettings = () => {
    dispatch('settings', widget);
  };

  const handleRemove = () => {
    dispatch('remove', widget);
  };
</script>

<div class="widget-wrapper" class:loading>
  <header class="widget-header">
    <div class="widget-title-section">
      {#if editable}
        <div class="widget-drag-handle" title="Przeciągnij aby przesunąć">
          <GripVertical size={16} />
        </div>
      {/if}
      <h3 class="widget-title">{widgetTitle}</h3>
    </div>

    {#if editable}
      <div class="widget-actions">
        <button
          class="widget-btn"
          on:click={handleSettings}
          title="Ustawienia widgeta"
          aria-label="Widget settings"
        >
          <Settings2 size={16} />
        </button>
        <button
          class="widget-btn widget-btn-danger"
          on:click={handleRemove}
          title="Usuń widget"
          aria-label="Remove widget"
        >
          <X size={16} />
        </button>
      </div>
    {/if}
  </header>

  <main class="widget-content">
    {#if loading}
      <div class="widget-loading">
        <div class="loading-spinner"></div>
        <span>Ładowanie...</span>
      </div>
    {:else}
      <slot />
    {/if}
  </main>
</div>

<style>
  .widget-wrapper {
    height: 100%;
    display: flex;
    flex-direction: column;
    background-color: var(--bg-card);
    border-radius: var(--radius-lg);
    overflow: hidden;
  }

  .widget-wrapper.loading {
    opacity: 0.7;
    pointer-events: none;
  }

  .widget-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0.75rem 1rem;
    background-color: var(--bg-secondary);
    border-bottom: 1px solid var(--border);
  }

  .widget-title-section {
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }

  .widget-drag-handle {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 24px;
    height: 24px;
    color: var(--text-muted);
    cursor: grab;
    border-radius: var(--radius-sm);
    transition: all var(--transition-fast);
  }

  .widget-drag-handle:hover {
    color: var(--text-primary);
    background-color: var(--bg-hover);
  }

  .widget-drag-handle:active {
    cursor: grabbing;
  }

  .widget-title {
    font-size: 0.875rem;
    font-weight: 600;
    color: var(--text-primary);
    margin: 0;
  }

  .widget-actions {
    display: flex;
    align-items: center;
    gap: 0.25rem;
  }

  .widget-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 28px;
    height: 28px;
    background: none;
    border: none;
    color: var(--text-muted);
    cursor: pointer;
    border-radius: var(--radius-sm);
    transition: all var(--transition-fast);
  }

  .widget-btn:hover {
    color: var(--text-primary);
    background-color: var(--bg-hover);
  }

  .widget-btn-danger:hover {
    color: #ef4444;
  }

  .widget-content {
    flex: 1;
    padding: 1rem;
    overflow: auto;
  }

  .widget-loading {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100%;
    gap: 1rem;
    color: var(--text-muted);
  }

  .loading-spinner {
    width: 24px;
    height: 24px;
    border: 2px solid var(--border);
    border-top-color: var(--accent-primary);
    border-radius: 50%;
    animation: spin 1s linear infinite;
  }

  @keyframes spin {
    from { transform: rotate(0deg); }
    to { transform: rotate(360deg); }
  }
</style>